# Form implementation generated from reading ui file 'FriendWidget.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FriendWidgetQt(object):
    def setupUi(self, FriendWidgetQt):
        FriendWidgetQt.setObjectName("FriendWidgetQt")
        FriendWidgetQt.resize(674, 300)
        self.Friend_wrapper = QtWidgets.QFrame(parent=FriendWidgetQt)
        self.Friend_wrapper.setGeometry(QtCore.QRect(90, 60, 501, 80))
        self.Friend_wrapper.setMinimumSize(QtCore.QSize(0, 80))
        self.Friend_wrapper.setMaximumSize(QtCore.QSize(1000, 80))
        self.Friend_wrapper.setStyleSheet("QFrame, QPushButton {\n"
"background-color:#323338;\n"
"border-radius:15%;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size:20px;\n"
"    color:white;\n"
"}")
        self.Friend_wrapper.setObjectName("Friend_wrapper")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Friend_wrapper)
        self.horizontalLayout.setContentsMargins(-1, -1, 40, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FriendIcoNick = QtWidgets.QFrame(parent=self.Friend_wrapper)
        self.FriendIcoNick.setObjectName("FriendIcoNick")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FriendIcoNick)
        self.horizontalLayout_2.setContentsMargins(10, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UserIcon = QtWidgets.QPushButton(parent=self.FriendIcoNick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserIcon.sizePolicy().hasHeightForWidth())
        self.UserIcon.setSizePolicy(sizePolicy)
        self.UserIcon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.UserIcon.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:25px;\n"
"color:White;\n"
"font-size:25px;\n"
"text-align:center;\n"
"")
        self.UserIcon.setObjectName("UserIcon")
        self.horizontalLayout_2.addWidget(self.UserIcon)
        self.UserNick = QtWidgets.QLabel(parent=self.FriendIcoNick)
        self.UserNick.setStyleSheet("font-size:20px;\n"
"color:white;")
        self.UserNick.setObjectName("UserNick")
        self.horizontalLayout_2.addWidget(self.UserNick)
        self.horizontalLayout.addWidget(self.FriendIcoNick)
        self.delete_friend = QtWidgets.QPushButton(parent=self.Friend_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_friend.sizePolicy().hasHeightForWidth())
        self.delete_friend.setSizePolicy(sizePolicy)
        self.delete_friend.setMinimumSize(QtCore.QSize(50, 50))
        self.delete_friend.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delete_friend.setStyleSheet("border:none;")
        self.delete_friend.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/person_remove_46dp_BB271A_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_friend.setIcon(icon)
        self.delete_friend.setIconSize(QtCore.QSize(40, 40))
        self.delete_friend.setObjectName("delete_friend")
        self.horizontalLayout.addWidget(self.delete_friend)
        self.horizontalLayout.setStretch(0, 3)

        self.retranslateUi(FriendWidgetQt)
        QtCore.QMetaObject.connectSlotsByName(FriendWidgetQt)

    def retranslateUi(self, FriendWidgetQt):
        _translate = QtCore.QCoreApplication.translate
        FriendWidgetQt.setWindowTitle(_translate("FriendWidgetQt", "Form"))
        self.UserIcon.setText(_translate("FriendWidgetQt", "U"))
        self.UserNick.setText(_translate("FriendWidgetQt", "Имя пользователя"))
