# Form implementation generated from reading ui file 'AddClientWidget.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(542, 225)
        self.Friend_wrapper = QtWidgets.QFrame(parent=Form)
        self.Friend_wrapper.setGeometry(QtCore.QRect(10, 60, 471, 80))
        self.Friend_wrapper.setMinimumSize(QtCore.QSize(0, 80))
        self.Friend_wrapper.setMaximumSize(QtCore.QSize(1000, 80))
        self.Friend_wrapper.setStyleSheet("QFrame, QPushButton {\n"
"background-color:#323338;\n"
"border-radius:15%;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size:20px;\n"
"    color:white;\n"
"}")
        self.Friend_wrapper.setObjectName("Friend_wrapper")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Friend_wrapper)
        self.horizontalLayout.setContentsMargins(-1, -1, 40, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FriendIcoNick = QtWidgets.QFrame(parent=self.Friend_wrapper)
        self.FriendIcoNick.setObjectName("FriendIcoNick")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FriendIcoNick)
        self.horizontalLayout_2.setContentsMargins(10, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UserIcon = QtWidgets.QPushButton(parent=self.FriendIcoNick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserIcon.sizePolicy().hasHeightForWidth())
        self.UserIcon.setSizePolicy(sizePolicy)
        self.UserIcon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.UserIcon.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:25px;\n"
"color:White;\n"
"font-size:25px;\n"
"text-align:center;\n"
"")
        self.UserIcon.setObjectName("UserIcon")
        self.horizontalLayout_2.addWidget(self.UserIcon)
        self.UserNick = QtWidgets.QLabel(parent=self.FriendIcoNick)
        self.UserNick.setStyleSheet("font-size:20px;\n"
"color:white;")
        self.UserNick.setObjectName("UserNick")
        self.horizontalLayout_2.addWidget(self.UserNick)
        self.horizontalLayout.addWidget(self.FriendIcoNick)
        self.send_request = QtWidgets.QPushButton(parent=self.Friend_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_request.sizePolicy().hasHeightForWidth())
        self.send_request.setSizePolicy(sizePolicy)
        self.send_request.setMinimumSize(QtCore.QSize(50, 50))
        self.send_request.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.send_request.setStyleSheet("border:none;")
        self.send_request.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/person_add_46dp_018741_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.send_request.setIcon(icon)
        self.send_request.setIconSize(QtCore.QSize(40, 40))
        self.send_request.setObjectName("send_request")
        self.horizontalLayout.addWidget(self.send_request)
        self.recall_request = QtWidgets.QPushButton(parent=self.Friend_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recall_request.sizePolicy().hasHeightForWidth())
        self.recall_request.setSizePolicy(sizePolicy)
        self.recall_request.setMinimumSize(QtCore.QSize(50, 50))
        self.recall_request.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.recall_request.setStyleSheet("border:none;")
        self.recall_request.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icon/person_cancel_46dp_8B1A10_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.recall_request.setIcon(icon1)
        self.recall_request.setIconSize(QtCore.QSize(40, 40))
        self.recall_request.setObjectName("recall_request")
        self.horizontalLayout.addWidget(self.recall_request)
        self.AlreadyFriend = QtWidgets.QLabel(parent=self.Friend_wrapper)
        self.AlreadyFriend.setObjectName("AlreadyFriend")
        self.horizontalLayout.addWidget(self.AlreadyFriend)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.UserIcon.setText(_translate("Form", "U"))
        self.UserNick.setText(_translate("Form", "Имя пользователя"))
        self.AlreadyFriend.setText(_translate("Form", "В друзьях"))
