# Form implementation generated from reading ui file 'GroupsListRequests.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Groups_page(object):
    def setupUi(self, Groups_page):
        Groups_page.setObjectName("Groups_page")
        Groups_page.resize(706, 721)
        self.verticalLayout = QtWidgets.QVBoxLayout(Groups_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Wrapper = QtWidgets.QFrame(parent=Groups_page)
        self.Wrapper.setStyleSheet("background-color:rgba(16,19,23,255);")
        self.Wrapper.setObjectName("Wrapper")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Wrapper)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu = QtWidgets.QFrame(parent=self.Wrapper)
        self.menu.setMinimumSize(QtCore.QSize(100, 100))
        self.menu.setStyleSheet("QFrame {\n"
"    border-bottom:3px solid white;\n"
"    background-color:rgba(34,35,39,255);\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    font-size:22px;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    background-color:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Эффект туманности сверху с прозрачностью */\n"
"    background-color: rgba(229, 229, 229, 55)\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgba(229, 229, 229, 55);\n"
"}\n"
"")
        self.menu.setObjectName("menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout.setContentsMargins(0, 12, 1, 11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalFrame = QtWidgets.QFrame(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(200, 70))
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame.setStyleSheet("QFrame {\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Эффект туманности сверху с прозрачностью */\n"
"    background-color: rgba(229, 229, 229, 55)\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgba(229, 229, 229, 55);\n"
"}")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.horizontalFrame)
        self.widget.setMinimumSize(QtCore.QSize(200, 70))
        self.widget.setMaximumSize(QtCore.QSize(91, 16777215))
        self.widget.setStyleSheet("QWidget {\n"
"background:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Эффект туманности сверху с прозрачностью */\n"
"    background-color: rgba(229, 229, 229, 55)\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgba(229, 229, 229, 55);\n"
"}")
        self.widget.setObjectName("widget")
        self.requests_button = QtWidgets.QPushButton(parent=self.widget)
        self.requests_button.setGeometry(QtCore.QRect(0, 0, 200, 47))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requests_button.sizePolicy().hasHeightForWidth())
        self.requests_button.setSizePolicy(sizePolicy)
        self.requests_button.setMinimumSize(QtCore.QSize(200, 0))
        self.requests_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.requests_button.setCheckable(False)
        self.requests_button.setObjectName("requests_button")
        self.groups_alert = QtWidgets.QPushButton(parent=self.widget)
        self.groups_alert.setGeometry(QtCore.QRect(170, 10, 10, 10))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groups_alert.sizePolicy().hasHeightForWidth())
        self.groups_alert.setSizePolicy(sizePolicy)
        self.groups_alert.setMaximumSize(QtCore.QSize(10, 10))
        self.groups_alert.setStyleSheet("border:1px solid #DA3E44;\n"
"background:#DA3E44;\n"
"border-radius:5%;\n"
"text-align: center; ")
        self.groups_alert.setText("")
        self.groups_alert.setObjectName("groups_alert")
        self.horizontalLayout_2.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.horizontalFrame, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.create_group = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_group.sizePolicy().hasHeightForWidth())
        self.create_group.setSizePolicy(sizePolicy)
        self.create_group.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_group.setObjectName("create_group")
        self.horizontalLayout.addWidget(self.create_group)
        self.groups_list = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groups_list.sizePolicy().hasHeightForWidth())
        self.groups_list.setSizePolicy(sizePolicy)
        self.groups_list.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.groups_list.setObjectName("groups_list")
        self.horizontalLayout.addWidget(self.groups_list)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.menu)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.Wrapper)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.Wrapper)

        self.retranslateUi(Groups_page)
        QtCore.QMetaObject.connectSlotsByName(Groups_page)

    def retranslateUi(self, Groups_page):
        _translate = QtCore.QCoreApplication.translate
        Groups_page.setWindowTitle(_translate("Groups_page", "Form"))
        self.requests_button.setText(_translate("Groups_page", "Приглашения"))
        self.create_group.setText(_translate("Groups_page", "Создать группу"))
        self.groups_list.setText(_translate("Groups_page", "Все группы"))
