# Form implementation generated from reading ui file 'AddFriendWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddFriend(object):
    def setupUi(self, AddFriend):
        AddFriend.setObjectName("AddFriend")
        AddFriend.resize(760, 682)
        self.Column = QtWidgets.QFrame(parent=AddFriend)
        self.Column.setGeometry(QtCore.QRect(10, 8, 741, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Column.sizePolicy().hasHeightForWidth())
        self.Column.setSizePolicy(sizePolicy)
        self.Column.setMinimumSize(QtCore.QSize(50, 50))
        self.Column.setStyleSheet("background-color:rgba(16,19,23,255);")
        self.Column.setObjectName("Column")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Column)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_frane = QtWidgets.QFrame(parent=self.Column)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_frane.sizePolicy().hasHeightForWidth())
        self.search_frane.setSizePolicy(sizePolicy)
        self.search_frane.setMinimumSize(QtCore.QSize(0, 150))
        self.search_frane.setStyleSheet("")
        self.search_frane.setObjectName("search_frane")
        self.search_field = QtWidgets.QHBoxLayout(self.search_frane)
        self.search_field.setContentsMargins(15, 0, 15, 0)
        self.search_field.setSpacing(15)
        self.search_field.setObjectName("search_field")
        self.nickname_input = QtWidgets.QLineEdit(parent=self.search_frane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nickname_input.sizePolicy().hasHeightForWidth())
        self.nickname_input.setSizePolicy(sizePolicy)
        self.nickname_input.setMinimumSize(QtCore.QSize(150, 50))
        self.nickname_input.setMaximumSize(QtCore.QSize(700, 16777215))
        self.nickname_input.setStyleSheet("QLineEdit {\n"
" width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius:20%;\n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"background-color:#323338;\n"
"font-size:20px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#656c76;\n"
"color:black;\n"
"background-image: url(:/icons/icon/search_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg); \n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"}")
        self.nickname_input.setText("")
        self.nickname_input.setObjectName("nickname_input")
        self.search_field.addWidget(self.nickname_input)
        self.Search_button = QtWidgets.QPushButton(parent=self.search_frane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_button.sizePolicy().hasHeightForWidth())
        self.Search_button.setSizePolicy(sizePolicy)
        self.Search_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Search_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Search_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Search_button.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border:none;\n"
"border-radius:15%;\n"
"border:3px solid white;")
        self.Search_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/search_53dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Search_button.setIcon(icon)
        self.Search_button.setIconSize(QtCore.QSize(35, 35))
        self.Search_button.setObjectName("Search_button")
        self.search_field.addWidget(self.Search_button, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.search_frane, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.Freinds_Layout = QtWidgets.QFrame(parent=self.Column)
        self.Freinds_Layout.setObjectName("Freinds_Layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Freinds_Layout)
        self.verticalLayout_3.setContentsMargins(15, 0, 15, 0)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FriendScroll = QtWidgets.QListWidget(parent=self.Freinds_Layout)
        self.FriendScroll.setMinimumSize(QtCore.QSize(200, 0))
        self.FriendScroll.setStyleSheet("QListWidget {\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"QListWidget::item\n"
"{\n"
"    background:none; \n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"           border:none;\n"
"            width:10px;\n"
"             height:20px;\n"
"                                                            \n"
"  }\n"
"                                                        \n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"         heigth:0;\n"
" }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"               background: none;\n"
" }\n"
"  QScrollBar::add-line:vertical {\n"
"               height: 0px;\n"
"  }\n"
" QScrollBar::sub-line:vertical {\n"
"                 height: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {\n"
"               background: orange;\n"
"                min-height:10px;\n"
"                 border-radius: 5px;\n"
" }")
        self.FriendScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.FriendScroll.setObjectName("FriendScroll")
        self.verticalLayout_3.addWidget(self.FriendScroll)
        self.verticalLayout_2.addWidget(self.Freinds_Layout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 4)

        self.retranslateUi(AddFriend)
        QtCore.QMetaObject.connectSlotsByName(AddFriend)

    def retranslateUi(self, AddFriend):
        _translate = QtCore.QCoreApplication.translate
        AddFriend.setWindowTitle(_translate("AddFriend", "Form"))
        self.nickname_input.setPlaceholderText(_translate("AddFriend", "Введите никнейм друга"))
