# Form implementation generated from reading ui file 'FriendOptionWidget.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FriendOption(object):
    def setupUi(self, FriendOption):
        FriendOption.setObjectName("FriendOption")
        FriendOption.resize(550, 300)
        self.Friend_wrapper = QtWidgets.QFrame(parent=FriendOption)
        self.Friend_wrapper.setGeometry(QtCore.QRect(30, 60, 501, 80))
        self.Friend_wrapper.setMinimumSize(QtCore.QSize(0, 80))
        self.Friend_wrapper.setMaximumSize(QtCore.QSize(1000, 80))
        self.Friend_wrapper.setStyleSheet("QFrame, QPushButton {\n"
"background-color:#323338;\n"
"border-radius:15%;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size:20px;\n"
"    color:white;\n"
"}")
        self.Friend_wrapper.setObjectName("Friend_wrapper")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Friend_wrapper)
        self.horizontalLayout.setContentsMargins(-1, -1, 40, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FriendNickWrapp = QtWidgets.QFrame(parent=self.Friend_wrapper)
        self.FriendNickWrapp.setObjectName("FriendNickWrapp")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FriendNickWrapp)
        self.horizontalLayout_2.setContentsMargins(10, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FriendIcon = QtWidgets.QPushButton(parent=self.FriendNickWrapp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FriendIcon.sizePolicy().hasHeightForWidth())
        self.FriendIcon.setSizePolicy(sizePolicy)
        self.FriendIcon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.FriendIcon.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:25px;\n"
"color:White;\n"
"font-size:25px;\n"
"text-align:center;\n"
"")
        self.FriendIcon.setObjectName("FriendIcon")
        self.horizontalLayout_2.addWidget(self.FriendIcon)
        self.FriendName = QtWidgets.QLabel(parent=self.FriendNickWrapp)
        self.FriendName.setStyleSheet("font-size:20px;\n"
"color:white;")
        self.FriendName.setObjectName("FriendName")
        self.horizontalLayout_2.addWidget(self.FriendName)
        self.horizontalLayout.addWidget(self.FriendNickWrapp)
        self.add_to_group_box = QtWidgets.QCheckBox(parent=self.Friend_wrapper)
        self.add_to_group_box.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 23px;\n"
"    height: 23px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"    background-image: url(:/icons/icon/check_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg);\n"
"    background-position:center;\n"
"}")
        self.add_to_group_box.setText("")
        self.add_to_group_box.setObjectName("add_to_group_box")
        self.horizontalLayout.addWidget(self.add_to_group_box)
        self.horizontalLayout.setStretch(0, 3)

        self.retranslateUi(FriendOption)
        QtCore.QMetaObject.connectSlotsByName(FriendOption)

    def retranslateUi(self, FriendOption):
        _translate = QtCore.QCoreApplication.translate
        FriendOption.setWindowTitle(_translate("FriendOption", "Form"))
        self.FriendIcon.setText(_translate("FriendOption", "G"))
        self.FriendName.setText(_translate("FriendOption", "Имя пользователя"))
