# Form implementation generated from reading ui file 'InviteUserDial.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserInviteDial(object):
    def setupUi(self, UserInviteDial):
        UserInviteDial.setObjectName("UserInviteDial")
        UserInviteDial.resize(493, 603)
        self.horizontalLayout = QtWidgets.QHBoxLayout(UserInviteDial)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GroupInviteDialog = QtWidgets.QFrame(parent=UserInviteDial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupInviteDialog.sizePolicy().hasHeightForWidth())
        self.GroupInviteDialog.setSizePolicy(sizePolicy)
        self.GroupInviteDialog.setMinimumSize(QtCore.QSize(471, 581))
        self.GroupInviteDialog.setStyleSheet("QFrame {\n"
"background-color:rgba(16,19,23,255);\n"
"border:1px solid white;\n"
"border-radius:45px;\n"
"}")
        self.GroupInviteDialog.setObjectName("GroupInviteDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GroupInviteDialog)
        self.verticalLayout.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.GroupInviteDialog)
        self.label_2.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.FriendsList = QtWidgets.QFrame(parent=self.GroupInviteDialog)
        self.FriendsList.setStyleSheet("border:none;")
        self.FriendsList.setObjectName("FriendsList")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FriendsList)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.friend_list = QtWidgets.QListWidget(parent=self.FriendsList)
        self.friend_list.setObjectName("friend_list")
        self.verticalLayout_4.addWidget(self.friend_list)
        self.invite_users_button = QtWidgets.QPushButton(parent=self.FriendsList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invite_users_button.sizePolicy().hasHeightForWidth())
        self.invite_users_button.setSizePolicy(sizePolicy)
        self.invite_users_button.setMinimumSize(QtCore.QSize(151, 50))
        self.invite_users_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.invite_users_button.setStyleSheet(" QPushButton {\n"
"border:1px solid orange;\n"
"border-radius:25%;\n"
"background-color:orange;\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 211, 121, 200);\n"
"    border:1px solid rgba(255, 211, 121, 200);\n"
"}")
        self.invite_users_button.setObjectName("invite_users_button")
        self.verticalLayout_4.addWidget(self.invite_users_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.FriendsList)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.GroupInviteDialog)

        self.retranslateUi(UserInviteDial)
        QtCore.QMetaObject.connectSlotsByName(UserInviteDial)

    def retranslateUi(self, UserInviteDial):
        _translate = QtCore.QCoreApplication.translate
        UserInviteDial.setWindowTitle(_translate("UserInviteDial", "Form"))
        self.label_2.setText(_translate("UserInviteDial", "Пригласить друзей в группу"))
        self.invite_users_button.setText(_translate("UserInviteDial", "Пригласить"))
