# Form implementation generated from reading ui file 'ChangeStatus.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(200, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Menu.sizePolicy().hasHeightForWidth())
        Menu.setSizePolicy(sizePolicy)
        Menu.setMinimumSize(QtCore.QSize(200, 240))
        Menu.setMaximumSize(QtCore.QSize(200, 16777215))
        Menu.setStyleSheet("QWidget#Menu {\n"
"background-color:#232528;\n"
"}\n"
"\n"
"QPushButton {\n"
"  border:none;\n"
"  font-size:18px;\n"
"  color:white;\n"
"  text-align:left;\n"
"}\n"
"QFrame:hover {\n"
" background-color:rgba(229, 229, 229, 50);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Menu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Wrapper = QtWidgets.QVBoxLayout()
        self.Wrapper.setObjectName("Wrapper")
        self.horizontalFrame_5 = QtWidgets.QFrame(parent=Menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_5.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_5.setSizePolicy(sizePolicy)
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Custom = QtWidgets.QPushButton(parent=self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Custom.sizePolicy().hasHeightForWidth())
        self.Custom.setSizePolicy(sizePolicy)
        self.Custom.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Custom.setObjectName("Custom")
        self.horizontalLayout_5.addWidget(self.Custom)
        self.Wrapper.addWidget(self.horizontalFrame_5)
        self.verticalLayout.addLayout(self.Wrapper)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.Custom.setText(_translate("Menu", "Создать свой"))
