# Form implementation generated from reading ui file 'MiniProfile.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(473, 470)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WrapperForProfile = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WrapperForProfile.sizePolicy().hasHeightForWidth())
        self.WrapperForProfile.setSizePolicy(sizePolicy)
        self.WrapperForProfile.setMinimumSize(QtCore.QSize(250, 340))
        self.WrapperForProfile.setMaximumSize(QtCore.QSize(300, 400))
        self.WrapperForProfile.setStyleSheet("QFrame {\n"
"background-color:rgba(16,19,23,255);\n"
"border:1px solid white;\n"
"}")
        self.WrapperForProfile.setObjectName("WrapperForProfile")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.WrapperForProfile)
        self.verticalLayout_2.setContentsMargins(11, -1, 11, 15)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LogoField = QtWidgets.QFrame(parent=self.WrapperForProfile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoField.sizePolicy().hasHeightForWidth())
        self.LogoField.setSizePolicy(sizePolicy)
        self.LogoField.setMinimumSize(QtCore.QSize(0, 100))
        self.LogoField.setStyleSheet("QFrame {\n"
" border:none;\n"
"}")
        self.LogoField.setObjectName("LogoField")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.LogoField)
        self.horizontalLayout_4.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(parent=self.LogoField)
        self.widget.setMinimumSize(QtCore.QSize(0, 70))
        self.widget.setMaximumSize(QtCore.QSize(75, 75))
        self.widget.setStyleSheet("background-color:none;")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QPushButton(parent=self.widget)
        self.logo.setGeometry(QtCore.QRect(0, 0, 75, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(75, 75))
        self.logo.setMaximumSize(QtCore.QSize(60, 65))
        self.logo.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:37%;\n"
"color:White;\n"
"font-size:32px;\n"
"")
        self.logo.setObjectName("logo")
        self.ActivityIndicator_2 = QtWidgets.QPushButton(parent=self.widget)
        self.ActivityIndicator_2.setGeometry(QtCore.QRect(50, 50, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivityIndicator_2.sizePolicy().hasHeightForWidth())
        self.ActivityIndicator_2.setSizePolicy(sizePolicy)
        self.ActivityIndicator_2.setMinimumSize(QtCore.QSize(30, 30))
        self.ActivityIndicator_2.setMaximumSize(QtCore.QSize(25, 25))
        self.ActivityIndicator_2.setStyleSheet("background-color:#008000;\n"
"border-radius:15px;\n"
"color:White;\n"
"border:6px solid rgba(16,19,23,255);\n"
"\n"
"")
        self.ActivityIndicator_2.setText("")
        self.ActivityIndicator_2.setObjectName("ActivityIndicator_2")
        self.horizontalLayout_4.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.LogoField)
        self.LogoStatusNickname = QtWidgets.QFrame(parent=self.WrapperForProfile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoStatusNickname.sizePolicy().hasHeightForWidth())
        self.LogoStatusNickname.setSizePolicy(sizePolicy)
        self.LogoStatusNickname.setStyleSheet("border:none;")
        self.LogoStatusNickname.setObjectName("LogoStatusNickname")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.LogoStatusNickname)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.NickName = QtWidgets.QLabel(parent=self.LogoStatusNickname)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NickName.sizePolicy().hasHeightForWidth())
        self.NickName.setSizePolicy(sizePolicy)
        self.NickName.setStyleSheet("font-size:22px;\n"
"color:white;\n"
"border:none;")
        self.NickName.setWordWrap(True)
        self.NickName.setObjectName("NickName")
        self.verticalLayout_4.addWidget(self.NickName, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalFrame = QtWidgets.QFrame(parent=self.LogoStatusNickname)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setStyleSheet("border:none;\n"
"margin:0px;\n"
"padding:0px;")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(parent=self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.verticalFrame.setStyleSheet("border:none;")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color:white;\n"
"border:none;\n"
"font-size:16px;\n"
"margin-left:5px;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.Status_input = QtWidgets.QLineEdit(parent=self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status_input.sizePolicy().hasHeightForWidth())
        self.Status_input.setSizePolicy(sizePolicy)
        self.Status_input.setMinimumSize(QtCore.QSize(0, 45))
        self.Status_input.setStyleSheet("QLineEdit {\n"
"width:200px;\n"
"height:25px;\n"
"border: 2px solid #323338;\n"
"border-radius: 15px;\n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"background-color:#323338;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"background-color:#656c76;\n"
"color:black;\n"
"}")
        self.Status_input.setObjectName("Status_input")
        self.verticalLayout_3.addWidget(self.Status_input)
        self.horizontalLayout.addWidget(self.verticalFrame)
        self.verticalLayout_4.addWidget(self.horizontalFrame)
        self.verticalLayout_2.addWidget(self.LogoStatusNickname)
        self.SettingsAndActivity = QtWidgets.QFrame(parent=self.WrapperForProfile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsAndActivity.sizePolicy().hasHeightForWidth())
        self.SettingsAndActivity.setSizePolicy(sizePolicy)
        self.SettingsAndActivity.setMinimumSize(QtCore.QSize(0, 0))
        self.SettingsAndActivity.setMaximumSize(QtCore.QSize(16777215, 120))
        self.SettingsAndActivity.setStyleSheet("border:none;\n"
"background-color:#232528;\n"
"border-radius:15%;")
        self.SettingsAndActivity.setObjectName("SettingsAndActivity")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.SettingsAndActivity)
        self.vboxlayout.setObjectName("vboxlayout")
        self.OpenSettings = QtWidgets.QPushButton(parent=self.SettingsAndActivity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenSettings.sizePolicy().hasHeightForWidth())
        self.OpenSettings.setSizePolicy(sizePolicy)
        self.OpenSettings.setMinimumSize(QtCore.QSize(240, 45))
        self.OpenSettings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.OpenSettings.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    padding-left:33px;\n"
"    font-size:18px;\n"
"    color: #FFFFFF; /* Белый текст */\n"
"     background-image:;\n"
"    background-image: url(GUI/icon/edit_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg);\n"
"    background-repeat:no-repeat;\n"
"    background-position: left;\n"
"    border-radius:0;\n"
"    text-align:left;\n"
"}\n"
"QPushButton:hover {\n"
" background-color:rgba(229, 229, 229, 50);\n"
" border-radius:15%;\n"
"}\n"
"")
        self.OpenSettings.setObjectName("OpenSettings")
        self.vboxlayout.addWidget(self.OpenSettings, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.line = QtWidgets.QFrame(parent=self.SettingsAndActivity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(220, 0))
        self.line.setStyleSheet("background-color:#656c76;")
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.vboxlayout.addWidget(self.line, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Activity = QtWidgets.QFrame(parent=self.SettingsAndActivity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Activity.sizePolicy().hasHeightForWidth())
        self.Activity.setSizePolicy(sizePolicy)
        self.Activity.setMinimumSize(QtCore.QSize(250, 45))
        self.Activity.setMaximumSize(QtCore.QSize(16777215, 42))
        self.Activity.setStyleSheet("QFrame:hover {\n"
" background-color:rgba(229, 229, 229, 50);\n"
"}\n"
"")
        self.Activity.setObjectName("Activity")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Activity)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ActivityIndicator = QtWidgets.QPushButton(parent=self.Activity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivityIndicator.sizePolicy().hasHeightForWidth())
        self.ActivityIndicator.setSizePolicy(sizePolicy)
        self.ActivityIndicator.setMinimumSize(QtCore.QSize(15, 15))
        self.ActivityIndicator.setMaximumSize(QtCore.QSize(15, 15))
        self.ActivityIndicator.setStyleSheet("background-color:green;\n"
"border-radius:7%;\n"
"color:White;\n"
"\n"
"")
        self.ActivityIndicator.setText("")
        self.ActivityIndicator.setObjectName("ActivityIndicator")
        self.horizontalLayout_2.addWidget(self.ActivityIndicator, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ChangeActivity = QtWidgets.QPushButton(parent=self.Activity)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChangeActivity.sizePolicy().hasHeightForWidth())
        self.ChangeActivity.setSizePolicy(sizePolicy)
        self.ChangeActivity.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ChangeActivity.setStyleSheet("QPushButton {\n"
"    padding:3px;\n"
"    border: none;\n"
"    font-size:18px;\n"
"    color: #FFFFFF; /* Белый текст */\n"
"    background-image:url(GUI/icon/chevron_right_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg);\n"
"    background-repeat:no-repeat;    \n"
"    background-position:right;\n"
"    background-color:none;\n"
"    text-align:left;\n"
"}\n"
"")
        self.ChangeActivity.setObjectName("ChangeActivity")
        self.horizontalLayout_2.addWidget(self.ChangeActivity, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.vboxlayout.addWidget(self.Activity, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.SettingsAndActivity, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout.addWidget(self.WrapperForProfile)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.logo.setText(_translate("Form", "U"))
        self.NickName.setText(_translate("Form", "BYDLO"))
        self.label.setText(_translate("Form", "Статус"))
        self.OpenSettings.setText(_translate("Form", "Редактировать профиль"))
        self.ChangeActivity.setText(_translate("Form", "В сети"))
