# Form implementation generated from reading ui file 'GroupInviteDial.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupInviteDial(object):
    def setupUi(self, GroupInviteDial):
        GroupInviteDial.setObjectName("GroupInviteDial")
        GroupInviteDial.resize(842, 636)
        self.GroupInviteDialog = QtWidgets.QFrame(parent=GroupInviteDial)
        self.GroupInviteDialog.setGeometry(QtCore.QRect(200, 10, 471, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupInviteDialog.sizePolicy().hasHeightForWidth())
        self.GroupInviteDialog.setSizePolicy(sizePolicy)
        self.GroupInviteDialog.setStyleSheet("QFrame {\n"
"background-color:rgba(16,19,23,255);\n"
"border:1px solid white;\n"
"border-radius:45px;\n"
"}")
        self.GroupInviteDialog.setObjectName("GroupInviteDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GroupInviteDialog)
        self.verticalLayout.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.GroupInviteDialog)
        self.label_2.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.FriendsList = QtWidgets.QFrame(parent=self.GroupInviteDialog)
        self.FriendsList.setStyleSheet("border:none;")
        self.FriendsList.setObjectName("FriendsList")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FriendsList)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.friend_list = QtWidgets.QListWidget(parent=self.FriendsList)
        self.friend_list.setObjectName("friend_list")
        self.verticalLayout_4.addWidget(self.friend_list)
        self.createGroup_button = QtWidgets.QPushButton(parent=self.FriendsList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createGroup_button.sizePolicy().hasHeightForWidth())
        self.createGroup_button.setSizePolicy(sizePolicy)
        self.createGroup_button.setMinimumSize(QtCore.QSize(151, 50))
        self.createGroup_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createGroup_button.setStyleSheet(" QPushButton {\n"
"border:1px solid orange;\n"
"border-radius:25%;\n"
"background-color:orange;\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 211, 121, 200);\n"
"    border:1px solid rgba(255, 211, 121, 200);\n"
"}")
        self.createGroup_button.setObjectName("createGroup_button")
        self.verticalLayout_4.addWidget(self.createGroup_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.FriendsList)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(GroupInviteDial)
        QtCore.QMetaObject.connectSlotsByName(GroupInviteDial)

    def retranslateUi(self, GroupInviteDial):
        _translate = QtCore.QCoreApplication.translate
        GroupInviteDial.setWindowTitle(_translate("GroupInviteDial", "Form"))
        self.label_2.setText(_translate("GroupInviteDial", "Добавить друзей в беседу"))
        self.createGroup_button.setText(_translate("GroupInviteDial", "Добавить"))
