# Form implementation generated from reading ui file 'ServiceMessage.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ServiceMessage(object):
    def setupUi(self, ServiceMessage):
        ServiceMessage.setObjectName("ServiceMessage")
        ServiceMessage.resize(671, 300)
        self.Message_ = QtWidgets.QFrame(parent=ServiceMessage)
        self.Message_.setGeometry(QtCore.QRect(120, 50, 421, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Message_.sizePolicy().hasHeightForWidth())
        self.Message_.setSizePolicy(sizePolicy)
        self.Message_.setMinimumSize(QtCore.QSize(0, 100))
        self.Message_.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Message_.setStyleSheet("QFrame {\n"
"background-color:rgba(56, 56, 56, 80);\n"
"border-radius:25%;\n"
"border:2px solid transparent;\n"
"}\n"
"\n"
"QFrame:acrtive {\n"
"    border:none;\n"
"}")
        self.Message_.setObjectName("Message_")
        self.Message = QtWidgets.QVBoxLayout(self.Message_)
        self.Message.setContentsMargins(35, -1, -1, 15)
        self.Message.setSpacing(2)
        self.Message.setObjectName("Message")
        self.User = QtWidgets.QFrame(parent=self.Message_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.User.sizePolicy().hasHeightForWidth())
        self.User.setSizePolicy(sizePolicy)
        self.User.setMinimumSize(QtCore.QSize(30, 0))
        self.User.setStyleSheet("border:none;\n"
"background-color:none;")
        self.User.setObjectName("User")
        self._2 = QtWidgets.QHBoxLayout(self.User)
        self._2.setContentsMargins(-1, 0, -1, 5)
        self._2.setSpacing(15)
        self._2.setObjectName("_2")
        self.date_label = QtWidgets.QLabel(parent=self.User)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        self.date_label.setStyleSheet("color:grey;\n"
"font-size:16px;\n"
"border:none;")
        self.date_label.setObjectName("date_label")
        self._2.addWidget(self.date_label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.Message.addWidget(self.User)
        self.Message_Text = QtWidgets.QLabel(parent=self.Message_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Message_Text.sizePolicy().hasHeightForWidth())
        self.Message_Text.setSizePolicy(sizePolicy)
        self.Message_Text.setStyleSheet("color:white;\n"
"font-size:16px;\n"
"border:none;\n"
"background-color:none;\n"
"\n"
"")
        self.Message_Text.setText("")
        self.Message_Text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Message_Text.setObjectName("Message_Text")
        self.Message.addWidget(self.Message_Text)
        self.horizontalFrame = QtWidgets.QFrame(parent=self.Message_)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalFrame.setStyleSheet("border:none;\n"
"margin:0px;\n"
"background-color:none;\n"
"padding:0px;")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(-1, 0, 11, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.WasSeenlabel = QtWidgets.QLabel(parent=self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WasSeenlabel.sizePolicy().hasHeightForWidth())
        self.WasSeenlabel.setSizePolicy(sizePolicy)
        self.WasSeenlabel.setStyleSheet("color:grey;\n"
"font-size:16px;\n"
"border:none;")
        self.WasSeenlabel.setObjectName("WasSeenlabel")
        self.horizontalLayout.addWidget(self.WasSeenlabel, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.Message.addWidget(self.horizontalFrame)
        self.Message.setStretch(0, 1)
        self.Message.setStretch(2, 1)

        self.retranslateUi(ServiceMessage)
        QtCore.QMetaObject.connectSlotsByName(ServiceMessage)

    def retranslateUi(self, ServiceMessage):
        _translate = QtCore.QCoreApplication.translate
        ServiceMessage.setWindowTitle(_translate("ServiceMessage", "Form"))
        self.date_label.setText(_translate("ServiceMessage", "<html><head/><body><p>ывфыв</p></body></html>"))
        self.WasSeenlabel.setText(_translate("ServiceMessage", "Seen"))
