# Form implementation generated from reading ui file 'CreateGroupWidget.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateGroupForm(object):
    def setupUi(self, CreateGroupForm):
        CreateGroupForm.setObjectName("CreateGroupForm")
        CreateGroupForm.resize(778, 640)
        self.CG_Wrapper = QtWidgets.QFrame(parent=CreateGroupForm)
        self.CG_Wrapper.setGeometry(QtCore.QRect(-10, 0, 761, 621))
        self.CG_Wrapper.setObjectName("CG_Wrapper")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CG_Wrapper)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Wrapper = QtWidgets.QFrame(parent=self.CG_Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wrapper.sizePolicy().hasHeightForWidth())
        self.Wrapper.setSizePolicy(sizePolicy)
        self.Wrapper.setMinimumSize(QtCore.QSize(500, 0))
        self.Wrapper.setObjectName("Wrapper")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Wrapper)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spinner_frame = QtWidgets.QFrame(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinner_frame.sizePolicy().hasHeightForWidth())
        self.spinner_frame.setSizePolicy(sizePolicy)
        self.spinner_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.spinner_frame.setObjectName("spinner_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.spinner_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.spinner_layout = QtWidgets.QHBoxLayout()
        self.spinner_layout.setObjectName("spinner_layout")
        self.label_4 = QtWidgets.QLabel(parent=self.spinner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_4.setObjectName("label_4")
        self.spinner_layout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addLayout(self.spinner_layout)
        self.verticalLayout_2.addWidget(self.spinner_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.GroupName_input = QtWidgets.QLineEdit(parent=self.Wrapper)
        self.GroupName_input.setMinimumSize(QtCore.QSize(250, 0))
        self.GroupName_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.GroupName_input.setInputMask("")
        self.GroupName_input.setText("")
        self.GroupName_input.setMaxLength(50)
        self.GroupName_input.setObjectName("GroupName_input")
        self.verticalLayout_2.addWidget(self.GroupName_input)
        self.is_private = QtWidgets.QCheckBox(parent=self.Wrapper)
        self.is_private.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_private.setObjectName("is_private")
        self.verticalLayout_2.addWidget(self.is_private)
        self.is_inviteGromAdmin = QtWidgets.QCheckBox(parent=self.Wrapper)
        self.is_inviteGromAdmin.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_inviteGromAdmin.setObjectName("is_inviteGromAdmin")
        self.verticalLayout_2.addWidget(self.is_inviteGromAdmin)
        self.is_password = QtWidgets.QCheckBox(parent=self.Wrapper)
        self.is_password.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_password.setObjectName("is_password")
        self.verticalLayout_2.addWidget(self.is_password)
        self.password_wrapper = QtWidgets.QFrame(parent=self.Wrapper)
        self.password_wrapper.setObjectName("password_wrapper")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.password_wrapper)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.password_wrapper)
        self.label_2.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.Password_input = QtWidgets.QLineEdit(parent=self.password_wrapper)
        self.Password_input.setMinimumSize(QtCore.QSize(250, 0))
        self.Password_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.Password_input.setText("")
        self.Password_input.setObjectName("Password_input")
        self.verticalLayout_3.addWidget(self.Password_input)
        self.label_3 = QtWidgets.QLabel(parent=self.password_wrapper)
        self.label_3.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.RepeatPassword_input = QtWidgets.QLineEdit(parent=self.password_wrapper)
        self.RepeatPassword_input.setMinimumSize(QtCore.QSize(250, 0))
        self.RepeatPassword_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.RepeatPassword_input.setText("")
        self.RepeatPassword_input.setObjectName("RepeatPassword_input")
        self.verticalLayout_3.addWidget(self.RepeatPassword_input)
        self.verticalLayout_2.addWidget(self.password_wrapper)
        self.verticalLayout.addWidget(self.Wrapper, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Errors = QtWidgets.QFrame(parent=self.CG_Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Errors.sizePolicy().hasHeightForWidth())
        self.Errors.setSizePolicy(sizePolicy)
        self.Errors.setMinimumSize(QtCore.QSize(500, 70))
        self.Errors.setStyleSheet("\n"
"border:4px solid #BF092F;\n"
"border-radius:25%;")
        self.Errors.setObjectName("Errors")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.Errors)
        self.vboxlayout.setContentsMargins(20, 10, -1, 10)
        self.vboxlayout.setObjectName("vboxlayout")
        self.ErrorText = QtWidgets.QLabel(parent=self.Errors)
        self.ErrorText.setStyleSheet("border:none;\n"
"font-size:18px;\n"
"color:#BF092F;")
        self.ErrorText.setObjectName("ErrorText")
        self.vboxlayout.addWidget(self.ErrorText)
        self.verticalLayout.addWidget(self.Errors, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.createGroup_button = QtWidgets.QPushButton(parent=self.CG_Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createGroup_button.sizePolicy().hasHeightForWidth())
        self.createGroup_button.setSizePolicy(sizePolicy)
        self.createGroup_button.setMinimumSize(QtCore.QSize(151, 50))
        self.createGroup_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createGroup_button.setStyleSheet(" QPushButton {\n"
"border:1px solid orange;\n"
"border-radius:25%;\n"
"background-color:orange;\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 211, 121, 200);\n"
"    border:1px solid rgba(255, 211, 121, 200);\n"
"}")
        self.createGroup_button.setObjectName("createGroup_button")
        self.verticalLayout.addWidget(self.createGroup_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(CreateGroupForm)
        QtCore.QMetaObject.connectSlotsByName(CreateGroupForm)

    def retranslateUi(self, CreateGroupForm):
        _translate = QtCore.QCoreApplication.translate
        CreateGroupForm.setWindowTitle(_translate("CreateGroupForm", "Form"))
        self.label_4.setText(_translate("CreateGroupForm", "Создаем группу"))
        self.label.setText(_translate("CreateGroupForm", "Название группы:"))
        self.GroupName_input.setPlaceholderText(_translate("CreateGroupForm", "Название группы"))
        self.is_private.setText(_translate("CreateGroupForm", "Приватная группа (только по приглашению)"))
        self.is_inviteGromAdmin.setText(_translate("CreateGroupForm", "Приглашения только от администратора"))
        self.is_password.setText(_translate("CreateGroupForm", "Вход по паролю"))
        self.label_2.setText(_translate("CreateGroupForm", "Пароль:"))
        self.Password_input.setPlaceholderText(_translate("CreateGroupForm", "Пароль"))
        self.label_3.setText(_translate("CreateGroupForm", "Повторить пароль:"))
        self.RepeatPassword_input.setPlaceholderText(_translate("CreateGroupForm", "Повторить пароль"))
        self.ErrorText.setText(_translate("CreateGroupForm", "Ошибка: поле \"Название группы\" не было заполнено"))
        self.createGroup_button.setText(_translate("CreateGroupForm", "Создать"))
