# Form implementation generated from reading ui file 'Chat.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Chat(object):
    def setupUi(self, Chat):
        Chat.setObjectName("Chat")
        Chat.resize(760, 682)
        self.MAIN = QtWidgets.QFrame(parent=Chat)
        self.MAIN.setGeometry(QtCore.QRect(-10, -10, 761, 681))
        self.MAIN.setObjectName("MAIN")
        self.MAIN_ChatLayout = QtWidgets.QHBoxLayout(self.MAIN)
        self.MAIN_ChatLayout.setSpacing(0)
        self.MAIN_ChatLayout.setObjectName("MAIN_ChatLayout")
        self.Column = QtWidgets.QFrame(parent=self.MAIN)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Column.sizePolicy().hasHeightForWidth())
        self.Column.setSizePolicy(sizePolicy)
        self.Column.setMinimumSize(QtCore.QSize(50, 50))
        self.Column.setStyleSheet("background-color:rgba(16,19,23,255);")
        self.Column.setObjectName("Column")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Column)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TopBar_2 = QtWidgets.QFrame(parent=self.Column)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopBar_2.sizePolicy().hasHeightForWidth())
        self.TopBar_2.setSizePolicy(sizePolicy)
        self.TopBar_2.setMinimumSize(QtCore.QSize(0, 100))
        self.TopBar_2.setStyleSheet("background-color:rgba(34,35,39,255);")
        self.TopBar_2.setObjectName("TopBar_2")
        self.TopBar = QtWidgets.QHBoxLayout(self.TopBar_2)
        self.TopBar.setContentsMargins(35, -1, 35, -1)
        self.TopBar.setObjectName("TopBar")
        self.UserIconAndNickInChat = QtWidgets.QFrame(parent=self.TopBar_2)
        self.UserIconAndNickInChat.setObjectName("UserIconAndNickInChat")
        self.LogoAndNickName = QtWidgets.QHBoxLayout(self.UserIconAndNickInChat)
        self.LogoAndNickName.setSpacing(25)
        self.LogoAndNickName.setObjectName("LogoAndNickName")
        self.UsersLogoinChat = QtWidgets.QPushButton(parent=self.UserIconAndNickInChat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersLogoinChat.sizePolicy().hasHeightForWidth())
        self.UsersLogoinChat.setSizePolicy(sizePolicy)
        self.UsersLogoinChat.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.UsersLogoinChat.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:25px;\n"
"color:White;\n"
"font-size:25px;\n"
"text-align:center;\n"
"")
        self.UsersLogoinChat.setObjectName("UsersLogoinChat")
        self.LogoAndNickName.addWidget(self.UsersLogoinChat)
        self.UsersNickInChat = QtWidgets.QLabel(parent=self.UserIconAndNickInChat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersNickInChat.sizePolicy().hasHeightForWidth())
        self.UsersNickInChat.setSizePolicy(sizePolicy)
        self.UsersNickInChat.setMinimumSize(QtCore.QSize(50, 50))
        self.UsersNickInChat.setStyleSheet("font-size:26px;\n"
"color:white;")
        self.UsersNickInChat.setObjectName("UsersNickInChat")
        self.LogoAndNickName.addWidget(self.UsersNickInChat)
        self.TopBar.addWidget(self.UserIconAndNickInChat, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.CallAndInfoButtons = QtWidgets.QFrame(parent=self.TopBar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CallAndInfoButtons.sizePolicy().hasHeightForWidth())
        self.CallAndInfoButtons.setSizePolicy(sizePolicy)
        self.CallAndInfoButtons.setObjectName("CallAndInfoButtons")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CallAndInfoButtons)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CallButton = QtWidgets.QPushButton(parent=self.CallAndInfoButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CallButton.sizePolicy().hasHeightForWidth())
        self.CallButton.setSizePolicy(sizePolicy)
        self.CallButton.setMinimumSize(QtCore.QSize(30, 30))
        self.CallButton.setMaximumSize(QtCore.QSize(40, 40))
        self.CallButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CallButton.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border:none;\n"
"border-radius:15%;\n"
"border:3px solid white;")
        self.CallButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/call_46dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.CallButton.setIcon(icon)
        self.CallButton.setIconSize(QtCore.QSize(30, 30))
        self.CallButton.setObjectName("CallButton")
        self.horizontalLayout_5.addWidget(self.CallButton)
        self.InfoButton = QtWidgets.QPushButton(parent=self.CallAndInfoButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoButton.sizePolicy().hasHeightForWidth())
        self.InfoButton.setSizePolicy(sizePolicy)
        self.InfoButton.setMinimumSize(QtCore.QSize(40, 40))
        self.InfoButton.setMaximumSize(QtCore.QSize(40, 40))
        self.InfoButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.InfoButton.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border:none;\n"
"border-radius:15%;\n"
"border:3px solid white;")
        self.InfoButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icon/info_46dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.InfoButton.setIcon(icon1)
        self.InfoButton.setIconSize(QtCore.QSize(30, 30))
        self.InfoButton.setObjectName("InfoButton")
        self.horizontalLayout_5.addWidget(self.InfoButton)
        self.TopBar.addWidget(self.CallAndInfoButtons)
        self.verticalLayout_2.addWidget(self.TopBar_2)
        self.MessahesInChat = QtWidgets.QFrame(parent=self.Column)
        self.MessahesInChat.setObjectName("MessahesInChat")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.MessahesInChat)
        self.verticalLayout_5.setContentsMargins(45, -1, 45, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ChatScroll = QtWidgets.QListWidget(parent=self.MessahesInChat)
        self.ChatScroll.setStyleSheet("QListWidget {\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"QListWidget::item\n"
"{\n"
"    background:none; \n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"           border:none;\n"
"            width:10px;\n"
"             height:20px;\n"
"                                                            \n"
"  }\n"
"                                                        \n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"         heigth:0;\n"
" }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"               background: none;\n"
" }\n"
"  QScrollBar::add-line:vertical {\n"
"               height: 0px;\n"
"  }\n"
" QScrollBar::sub-line:vertical {\n"
"                 height: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {\n"
"               background: orange;\n"
"                min-height:10px;\n"
"                 border-radius: 5px;\n"
" }")
        self.ChatScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.ChatScroll.setObjectName("ChatScroll")
        self.verticalLayout_5.addWidget(self.ChatScroll)
        self.verticalLayout_2.addWidget(self.MessahesInChat)
        self.ChatLayout = QtWidgets.QFrame(parent=self.Column)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatLayout.sizePolicy().hasHeightForWidth())
        self.ChatLayout.setSizePolicy(sizePolicy)
        self.ChatLayout.setMinimumSize(QtCore.QSize(0, 0))
        self.ChatLayout.setObjectName("ChatLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ChatLayout)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ChatInputLayout = QtWidgets.QFrame(parent=self.ChatLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatInputLayout.sizePolicy().hasHeightForWidth())
        self.ChatInputLayout.setSizePolicy(sizePolicy)
        self.ChatInputLayout.setObjectName("ChatInputLayout")
        self.Chat_input = QtWidgets.QHBoxLayout(self.ChatInputLayout)
        self.Chat_input.setSpacing(7)
        self.Chat_input.setObjectName("Chat_input")
        self.Chat_input_ = QtWidgets.QLineEdit(parent=self.ChatInputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Chat_input_.sizePolicy().hasHeightForWidth())
        self.Chat_input_.setSizePolicy(sizePolicy)
        self.Chat_input_.setMinimumSize(QtCore.QSize(400, 0))
        self.Chat_input_.setStyleSheet("QLineEdit {\n"
" width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius:20%;\n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"background-color:#323338;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#656c76;\n"
"color:black;\n"
"background-image: url(GUI/icon/search_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg); \n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"}")
        self.Chat_input_.setText("")
        self.Chat_input_.setObjectName("Chat_input_")
        self.Chat_input.addWidget(self.Chat_input_)
        self.Attcahment_button = QtWidgets.QPushButton(parent=self.ChatInputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Attcahment_button.sizePolicy().hasHeightForWidth())
        self.Attcahment_button.setSizePolicy(sizePolicy)
        self.Attcahment_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Attcahment_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Attcahment_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Attcahment_button.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border-radius:25%;\n"
"border:3px solid white;")
        self.Attcahment_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI/icon/attach_file_46dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Attcahment_button.setIcon(icon2)
        self.Attcahment_button.setIconSize(QtCore.QSize(30, 30))
        self.Attcahment_button.setObjectName("Attcahment_button")
        self.Chat_input.addWidget(self.Attcahment_button)
        self.Send_button = QtWidgets.QPushButton(parent=self.ChatInputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send_button.sizePolicy().hasHeightForWidth())
        self.Send_button.setSizePolicy(sizePolicy)
        self.Send_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Send_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Send_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Send_button.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border-radius:25%;\n"
"border:3px solid white;")
        self.Send_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("GUI/icon/send_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Send_button.setIcon(icon3)
        self.Send_button.setIconSize(QtCore.QSize(30, 30))
        self.Send_button.setObjectName("Send_button")
        self.Chat_input.addWidget(self.Send_button)
        self.verticalLayout_7.addWidget(self.ChatInputLayout)
        self.verticalLayout_2.addWidget(self.ChatLayout)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.setStretch(2, 1)
        self.MAIN_ChatLayout.addWidget(self.Column)

        self.retranslateUi(Chat)
        QtCore.QMetaObject.connectSlotsByName(Chat)

    def retranslateUi(self, Chat):
        _translate = QtCore.QCoreApplication.translate
        Chat.setWindowTitle(_translate("Chat", "Form"))
        self.UsersLogoinChat.setText(_translate("Chat", "G"))
        self.UsersNickInChat.setText(_translate("Chat", "Group-1"))
        self.Chat_input_.setPlaceholderText(_translate("Chat", "Введите сообщение"))
