# Form implementation generated from reading ui file 'DeleteFriend.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteFriend(object):
    def setupUi(self, DeleteFriend):
        DeleteFriend.setObjectName("DeleteFriend")
        DeleteFriend.resize(566, 227)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DeleteFriend.sizePolicy().hasHeightForWidth())
        DeleteFriend.setSizePolicy(sizePolicy)
        self.wrap = QtWidgets.QFrame(parent=DeleteFriend)
        self.wrap.setGeometry(QtCore.QRect(10, 10, 541, 211))
        self.wrap.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border-radius:25%;\n"
"border:3px solid white;")
        self.wrap.setObjectName("wrap")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wrap)
        self.verticalLayout_2.setContentsMargins(-1, 11, -1, 5)
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CloseMinimizeButtons = QtWidgets.QFrame(parent=self.wrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseMinimizeButtons.sizePolicy().hasHeightForWidth())
        self.CloseMinimizeButtons.setSizePolicy(sizePolicy)
        self.CloseMinimizeButtons.setStyleSheet("border:none;")
        self.CloseMinimizeButtons.setObjectName("CloseMinimizeButtons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.CloseMinimizeButtons)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addWidget(self.CloseMinimizeButtons, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.AddFriendWrapper = QtWidgets.QFrame(parent=self.wrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddFriendWrapper.sizePolicy().hasHeightForWidth())
        self.AddFriendWrapper.setSizePolicy(sizePolicy)
        self.AddFriendWrapper.setMaximumSize(QtCore.QSize(16777215, 200))
        self.AddFriendWrapper.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border:none;")
        self.AddFriendWrapper.setObjectName("AddFriendWrapper")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AddFriendWrapper)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.AddFriendWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color:white;\n"
"font-size:20px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ButtonsPlaceholder = QtWidgets.QFrame(parent=self.AddFriendWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonsPlaceholder.sizePolicy().hasHeightForWidth())
        self.ButtonsPlaceholder.setSizePolicy(sizePolicy)
        self.ButtonsPlaceholder.setStyleSheet("background-color:rgba(38,40,45,255);")
        self.ButtonsPlaceholder.setObjectName("ButtonsPlaceholder")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ButtonsPlaceholder)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Delete_button = QtWidgets.QPushButton(parent=self.ButtonsPlaceholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Delete_button.sizePolicy().hasHeightForWidth())
        self.Delete_button.setSizePolicy(sizePolicy)
        self.Delete_button.setMinimumSize(QtCore.QSize(90, 35))
        self.Delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Delete_button.setStyleSheet("border:3px solid #BB271A;\n"
"border-radius:10%;\n"
"background-color: #BB271A;\n"
"color: black;\n"
"font-size:20px;")
        self.Delete_button.setIconSize(QtCore.QSize(30, 30))
        self.Delete_button.setObjectName("Delete_button")
        self.horizontalLayout.addWidget(self.Delete_button)
        self.Block_button = QtWidgets.QPushButton(parent=self.ButtonsPlaceholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Block_button.sizePolicy().hasHeightForWidth())
        self.Block_button.setSizePolicy(sizePolicy)
        self.Block_button.setMinimumSize(QtCore.QSize(90, 35))
        self.Block_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Block_button.setStyleSheet("border:3px solid #BB271A;\n"
"border-radius:10%;\n"
"background-color: #BB271A;\n"
"color: black;\n"
"font-size:20px;")
        self.Block_button.setIconSize(QtCore.QSize(30, 30))
        self.Block_button.setObjectName("Block_button")
        self.horizontalLayout.addWidget(self.Block_button)
        self.ReturnButtom = QtWidgets.QPushButton(parent=self.ButtonsPlaceholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReturnButtom.sizePolicy().hasHeightForWidth())
        self.ReturnButtom.setSizePolicy(sizePolicy)
        self.ReturnButtom.setMinimumSize(QtCore.QSize(90, 35))
        self.ReturnButtom.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ReturnButtom.setStyleSheet("border:3px solid white;\n"
"border-radius:10%;\n"
"color: white;\n"
"font-size:20px;")
        self.ReturnButtom.setIconSize(QtCore.QSize(30, 30))
        self.ReturnButtom.setObjectName("ReturnButtom")
        self.horizontalLayout.addWidget(self.ReturnButtom)
        self.verticalLayout.addWidget(self.ButtonsPlaceholder, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.AddFriendWrapper, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)

        self.retranslateUi(DeleteFriend)
        QtCore.QMetaObject.connectSlotsByName(DeleteFriend)

    def retranslateUi(self, DeleteFriend):
        _translate = QtCore.QCoreApplication.translate
        DeleteFriend.setWindowTitle(_translate("DeleteFriend", "Dialog"))
        self.label.setText(_translate("DeleteFriend", "Вы уверены?"))
        self.Delete_button.setText(_translate("DeleteFriend", "Удалить"))
        self.Block_button.setText(_translate("DeleteFriend", "Заблокировать"))
        self.ReturnButtom.setText(_translate("DeleteFriend", "Отмена"))
