# Form implementation generated from reading ui file 'GroupSettings.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupSettings(object):
    def setupUi(self, GroupSettings):
        GroupSettings.setObjectName("GroupSettings")
        GroupSettings.resize(600, 622)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GroupSettings.sizePolicy().hasHeightForWidth())
        GroupSettings.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(GroupSettings)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Wrapper = QtWidgets.QFrame(parent=GroupSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wrapper.sizePolicy().hasHeightForWidth())
        self.Wrapper.setSizePolicy(sizePolicy)
        self.Wrapper.setMinimumSize(QtCore.QSize(600, 500))
        self.Wrapper.setStyleSheet("QFrame {\n"
"background-color:rgba(16,19,23,255);\n"
"border:1px solid white;\n"
"border-radius:45px;\n"
"}")
        self.Wrapper.setObjectName("Wrapper")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Wrapper)
        self.verticalLayout.setContentsMargins(5, 20, 5, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.Wrapper)
        self.label_2.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.spinner_frame = QtWidgets.QFrame(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinner_frame.sizePolicy().hasHeightForWidth())
        self.spinner_frame.setSizePolicy(sizePolicy)
        self.spinner_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.spinner_frame.setStyleSheet("border:none;")
        self.spinner_frame.setObjectName("spinner_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.spinner_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.spinner_layout = QtWidgets.QHBoxLayout()
        self.spinner_layout.setObjectName("spinner_layout")
        self.error_label = QtWidgets.QLabel(parent=self.spinner_frame)
        self.error_label.setStyleSheet("color:red;\n"
"font-size:16px;")
        self.error_label.setObjectName("error_label")
        self.spinner_layout.addWidget(self.error_label)
        self.info_label = QtWidgets.QLabel(parent=self.spinner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label.sizePolicy().hasHeightForWidth())
        self.info_label.setSizePolicy(sizePolicy)
        self.info_label.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.info_label.setObjectName("info_label")
        self.spinner_layout.addWidget(self.info_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_6.addLayout(self.spinner_layout)
        self.verticalLayout.addWidget(self.spinner_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.FriendsList = QtWidgets.QFrame(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FriendsList.sizePolicy().hasHeightForWidth())
        self.FriendsList.setSizePolicy(sizePolicy)
        self.FriendsList.setStyleSheet("border:none;")
        self.FriendsList.setObjectName("FriendsList")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FriendsList)
        self.verticalLayout_4.setSpacing(25)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.change_name = QtWidgets.QFrame(parent=self.FriendsList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_name.sizePolicy().hasHeightForWidth())
        self.change_name.setSizePolicy(sizePolicy)
        self.change_name.setObjectName("change_name")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.change_name)
        self.horizontalLayout_2.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.change_name)
        self.label_3.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.GroupName = QtWidgets.QLineEdit(parent=self.change_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupName.sizePolicy().hasHeightForWidth())
        self.GroupName.setSizePolicy(sizePolicy)
        self.GroupName.setMinimumSize(QtCore.QSize(250, 0))
        self.GroupName.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"}\n"
"\n"
"")
        self.GroupName.setInputMask("")
        self.GroupName.setText("")
        self.GroupName.setMaxLength(50)
        self.GroupName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.GroupName.setObjectName("GroupName")
        self.horizontalLayout_2.addWidget(self.GroupName)
        self.verticalLayout_4.addWidget(self.change_name)
        self.Wrapper_2 = QtWidgets.QFrame(parent=self.FriendsList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wrapper_2.sizePolicy().hasHeightForWidth())
        self.Wrapper_2.setSizePolicy(sizePolicy)
        self.Wrapper_2.setMinimumSize(QtCore.QSize(500, 0))
        self.Wrapper_2.setObjectName("Wrapper_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Wrapper_2)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.is_private = QtWidgets.QCheckBox(parent=self.Wrapper_2)
        self.is_private.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_private.setObjectName("is_private")
        self.verticalLayout_2.addWidget(self.is_private, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.is_inviteGromAdmin = QtWidgets.QCheckBox(parent=self.Wrapper_2)
        self.is_inviteGromAdmin.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_inviteGromAdmin.setObjectName("is_inviteGromAdmin")
        self.verticalLayout_2.addWidget(self.is_inviteGromAdmin)
        self.is_password = QtWidgets.QCheckBox(parent=self.Wrapper_2)
        self.is_password.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_password.setObjectName("is_password")
        self.verticalLayout_2.addWidget(self.is_password)
        self.change_password_button = QtWidgets.QPushButton(parent=self.Wrapper_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_password_button.sizePolicy().hasHeightForWidth())
        self.change_password_button.setSizePolicy(sizePolicy)
        self.change_password_button.setMinimumSize(QtCore.QSize(150, 35))
        self.change_password_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.change_password_button.setStyleSheet(" QPushButton {\n"
"border:1px solid orange;\n"
"border-radius:15%;\n"
"background-color:orange;\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 211, 121, 200);\n"
"    border:1px solid rgba(255, 211, 121, 200);\n"
"}")
        self.change_password_button.setObjectName("change_password_button")
        self.verticalLayout_2.addWidget(self.change_password_button)
        self.verticalLayout_4.addWidget(self.Wrapper_2)
        self.password_wrapper = QtWidgets.QFrame(parent=self.FriendsList)
        self.password_wrapper.setObjectName("password_wrapper")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.password_wrapper)
        self.verticalLayout_5.setContentsMargins(11, 0, 11, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.password_wrapper)
        self.label_4.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.Password_input = QtWidgets.QLineEdit(parent=self.password_wrapper)
        self.Password_input.setMinimumSize(QtCore.QSize(250, 0))
        self.Password_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.Password_input.setText("")
        self.Password_input.setObjectName("Password_input")
        self.verticalLayout_5.addWidget(self.Password_input)
        self.label_5 = QtWidgets.QLabel(parent=self.password_wrapper)
        self.label_5.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.RepeatPassword_input = QtWidgets.QLineEdit(parent=self.password_wrapper)
        self.RepeatPassword_input.setMinimumSize(QtCore.QSize(250, 0))
        self.RepeatPassword_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.RepeatPassword_input.setText("")
        self.RepeatPassword_input.setObjectName("RepeatPassword_input")
        self.verticalLayout_5.addWidget(self.RepeatPassword_input)
        self.verticalLayout_4.addWidget(self.password_wrapper)
        self.verticalLayout.addWidget(self.FriendsList, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.save_changes_button = QtWidgets.QPushButton(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_changes_button.sizePolicy().hasHeightForWidth())
        self.save_changes_button.setSizePolicy(sizePolicy)
        self.save_changes_button.setMinimumSize(QtCore.QSize(151, 50))
        self.save_changes_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_changes_button.setStyleSheet(" QPushButton {\n"
"border:1px solid orange;\n"
"border-radius:25%;\n"
"background-color:orange;\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 211, 121, 200);\n"
"    border:1px solid rgba(255, 211, 121, 200);\n"
"}")
        self.save_changes_button.setObjectName("save_changes_button")
        self.verticalLayout.addWidget(self.save_changes_button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.Wrapper)

        self.retranslateUi(GroupSettings)
        QtCore.QMetaObject.connectSlotsByName(GroupSettings)

    def retranslateUi(self, GroupSettings):
        _translate = QtCore.QCoreApplication.translate
        GroupSettings.setWindowTitle(_translate("GroupSettings", "Form"))
        self.label_2.setText(_translate("GroupSettings", "Настройки группы"))
        self.error_label.setText(_translate("GroupSettings", "TextLabel"))
        self.info_label.setText(_translate("GroupSettings", "Меняем настройки"))
        self.label_3.setText(_translate("GroupSettings", "Сменить название:"))
        self.GroupName.setPlaceholderText(_translate("GroupSettings", "Название группы"))
        self.is_private.setText(_translate("GroupSettings", "Приватная группа (только по приглашению)"))
        self.is_inviteGromAdmin.setText(_translate("GroupSettings", "Приглашения только от администратора"))
        self.is_password.setText(_translate("GroupSettings", "Вход по паролю"))
        self.change_password_button.setText(_translate("GroupSettings", "Сменить пароль"))
        self.label_4.setText(_translate("GroupSettings", "Введите новый пароль:"))
        self.Password_input.setPlaceholderText(_translate("GroupSettings", "Пароль"))
        self.label_5.setText(_translate("GroupSettings", "Повторить пароль:"))
        self.RepeatPassword_input.setPlaceholderText(_translate("GroupSettings", "Повторить пароль"))
        self.save_changes_button.setText(_translate("GroupSettings", "Сохранить"))
