# Form implementation generated from reading ui file 'GroupsList.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Groups_List(object):
    def setupUi(self, Groups_List):
        Groups_List.setObjectName("Groups_List")
        Groups_List.resize(771, 818)
        self.Column = QtWidgets.QFrame(parent=Groups_List)
        self.Column.setGeometry(QtCore.QRect(10, 60, 741, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Column.sizePolicy().hasHeightForWidth())
        self.Column.setSizePolicy(sizePolicy)
        self.Column.setMinimumSize(QtCore.QSize(50, 50))
        self.Column.setStyleSheet("background-color:rgba(16,19,23,255);")
        self.Column.setObjectName("Column")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Column)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groups_layout = QtWidgets.QFrame(parent=self.Column)
        self.groups_layout.setStyleSheet("QListWidget {\n"
"background:transparent;\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"QListWidget::item\n"
"{\n"
"    background:none; \n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"           border:none;\n"
"            width:10px;\n"
"             height:20px;\n"
"                                                            \n"
"  }\n"
"                                                        \n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"         heigth:0;\n"
" }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"               background: none;\n"
" }\n"
"  QScrollBar::add-line:vertical {\n"
"               height: 0px;\n"
"  }\n"
" QScrollBar::sub-line:vertical {\n"
"                 height: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {\n"
"               background: orange;\n"
"                min-height:10px;\n"
"                 border-radius: 5px;\n"
" }")
        self.groups_layout.setObjectName("groups_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groups_layout)
        self.verticalLayout_3.setContentsMargins(15, 20, 15, 15)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groups = QtWidgets.QPushButton(parent=self.groups_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groups.sizePolicy().hasHeightForWidth())
        self.groups.setSizePolicy(sizePolicy)
        self.groups.setMinimumSize(QtCore.QSize(80, 30))
        self.groups.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.groups.setStyleSheet(" QPushButton {\n"
"border:1px solid orange;\n"
"border-radius:15%;\n"
"background-color:orange;\n"
"color:white;\n"
"font-size:16px;\n"
"padding:5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 211, 121, 200);\n"
"    border:1px solid rgba(255, 211, 121, 200);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/icons8-refresh-20.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.groups.setIcon(icon)
        self.groups.setIconSize(QtCore.QSize(20, 20))
        self.groups.setObjectName("groups")
        self.verticalLayout_3.addWidget(self.groups, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.group_request = QtWidgets.QListWidget(parent=self.groups_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_request.sizePolicy().hasHeightForWidth())
        self.group_request.setSizePolicy(sizePolicy)
        self.group_request.setMinimumSize(QtCore.QSize(500, 0))
        self.group_request.setStyleSheet("QListWidget {\n"
"border:1px solid rgba(38,40,45,255);\n"
"border-left:none;\n"
"border-right:none;\n"
"border-top:none;\n"
"}\n"
"\n"
"")
        self.group_request.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.group_request.setObjectName("group_request")
        self.verticalLayout_3.addWidget(self.group_request, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.groups_layout)
        self.verticalLayout_2.setStretch(0, 4)

        self.retranslateUi(Groups_List)
        QtCore.QMetaObject.connectSlotsByName(Groups_List)

    def retranslateUi(self, Groups_List):
        _translate = QtCore.QCoreApplication.translate
        Groups_List.setWindowTitle(_translate("Groups_List", "Form"))
        self.groups.setText(_translate("Groups_List", "Обновить"))
