# Form implementation generated from reading ui file 'GroupsList.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Groups_List(object):
    def setupUi(self, Groups_List):
        Groups_List.setObjectName("Groups_List")
        Groups_List.resize(771, 818)
        self.Column = QtWidgets.QFrame(parent=Groups_List)
        self.Column.setGeometry(QtCore.QRect(10, 60, 741, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Column.sizePolicy().hasHeightForWidth())
        self.Column.setSizePolicy(sizePolicy)
        self.Column.setMinimumSize(QtCore.QSize(50, 50))
        self.Column.setStyleSheet("background-color:rgba(16,19,23,255);")
        self.Column.setObjectName("Column")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Column)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groups_layout = QtWidgets.QFrame(parent=self.Column)
        self.groups_layout.setStyleSheet("QListWidget {\n"
"background:transparent;\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"QListWidget::item\n"
"{\n"
"    background:none; \n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"           border:none;\n"
"            width:10px;\n"
"             height:20px;\n"
"                                                            \n"
"  }\n"
"                                                        \n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"         heigth:0;\n"
" }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"               background: none;\n"
" }\n"
"  QScrollBar::add-line:vertical {\n"
"               height: 0px;\n"
"  }\n"
" QScrollBar::sub-line:vertical {\n"
"                 height: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {\n"
"               background: orange;\n"
"                min-height:10px;\n"
"                 border-radius: 5px;\n"
" }")
        self.groups_layout.setObjectName("groups_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groups_layout)
        self.verticalLayout_3.setContentsMargins(15, 20, 15, 15)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalFrame = QtWidgets.QFrame(parent=self.groups_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_group_input = QtWidgets.QLineEdit(parent=self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_group_input.sizePolicy().hasHeightForWidth())
        self.search_group_input.setSizePolicy(sizePolicy)
        self.search_group_input.setMinimumSize(QtCore.QSize(450, 50))
        self.search_group_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:18px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.search_group_input.setInputMask("")
        self.search_group_input.setText("")
        self.search_group_input.setMaxLength(50)
        self.search_group_input.setObjectName("search_group_input")
        self.horizontalLayout.addWidget(self.search_group_input, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Search_button = QtWidgets.QPushButton(parent=self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_button.sizePolicy().hasHeightForWidth())
        self.Search_button.setSizePolicy(sizePolicy)
        self.Search_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Search_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Search_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Search_button.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border:none;\n"
"border-radius:15%;\n"
"border:3px solid white;")
        self.Search_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/search_53dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Search_button.setIcon(icon)
        self.Search_button.setIconSize(QtCore.QSize(35, 35))
        self.Search_button.setObjectName("Search_button")
        self.horizontalLayout.addWidget(self.Search_button)
        self.verticalLayout_3.addWidget(self.horizontalFrame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.group_request = QtWidgets.QListWidget(parent=self.groups_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_request.sizePolicy().hasHeightForWidth())
        self.group_request.setSizePolicy(sizePolicy)
        self.group_request.setMinimumSize(QtCore.QSize(500, 0))
        self.group_request.setStyleSheet("QListWidget {\n"
"border:1px solid rgba(38,40,45,255);\n"
"border-left:none;\n"
"border-right:none;\n"
"border-top:none;\n"
"}\n"
"\n"
"")
        self.group_request.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.group_request.setObjectName("group_request")
        self.verticalLayout_3.addWidget(self.group_request, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.groups_layout)
        self.verticalLayout_2.setStretch(0, 4)

        self.retranslateUi(Groups_List)
        QtCore.QMetaObject.connectSlotsByName(Groups_List)

    def retranslateUi(self, Groups_List):
        _translate = QtCore.QCoreApplication.translate
        Groups_List.setWindowTitle(_translate("Groups_List", "Form"))
        self.search_group_input.setPlaceholderText(_translate("Groups_List", "Название группы"))
