# Form implementation generated from reading ui file 'ChatInList.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 80, 281, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Friend = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Friend.setContentsMargins(11, 0, 11, 0)
        self.Friend.setSpacing(10)
        self.Friend.setObjectName("Friend")
        self.wrapp = QtWidgets.QWidget(parent=self.horizontalLayoutWidget)
        self.wrapp.setMaximumSize(QtCore.QSize(40, 40))
        self.wrapp.setStyleSheet("QWidget {\n"
"background:none;\n"
"}")
        self.wrapp.setObjectName("wrapp")
        self.user_logo = QtWidgets.QPushButton(parent=self.wrapp)
        self.user_logo.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.user_logo.setMaximumSize(QtCore.QSize(40, 40))
        self.user_logo.setStyleSheet("background-color:purple;\n"
"border-radius:17%;\n"
"font-size:16px;\n"
"color:white;")
        self.user_logo.setText("")
        self.user_logo.setObjectName("user_logo")
        self.ActivityIndicator_chatList = QtWidgets.QPushButton(parent=self.wrapp)
        self.ActivityIndicator_chatList.setGeometry(QtCore.QRect(30, 30, 10, 10))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivityIndicator_chatList.sizePolicy().hasHeightForWidth())
        self.ActivityIndicator_chatList.setSizePolicy(sizePolicy)
        self.ActivityIndicator_chatList.setMinimumSize(QtCore.QSize(10, 10))
        self.ActivityIndicator_chatList.setMaximumSize(QtCore.QSize(10, 10))
        self.ActivityIndicator_chatList.setStyleSheet("background-color:green;\n"
"border-radius:5%;\n"
"color:White;\n"
"\n"
"")
        self.ActivityIndicator_chatList.setText("")
        self.ActivityIndicator_chatList.setObjectName("ActivityIndicator_chatList")
        self.Friend.addWidget(self.wrapp)
        self.user_name = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.user_name.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;\n"
"background-color:none;")
        self.user_name.setObjectName("user_name")
        self.Friend.addWidget(self.user_name)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.user_name.setText(_translate("Form", "TextLabel"))
