# Form implementation generated from reading ui file 'AddFriend.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddFriend(object):
    def setupUi(self, AddFriend):
        AddFriend.setObjectName("AddFriend")
        AddFriend.resize(566, 227)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddFriend.sizePolicy().hasHeightForWidth())
        AddFriend.setSizePolicy(sizePolicy)
        self.horizontalFrame = QtWidgets.QFrame(parent=AddFriend)
        self.horizontalFrame.setGeometry(QtCore.QRect(10, 10, 541, 211))
        self.horizontalFrame.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border-radius:25%;\n"
"border:3px solid white;")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalFrame)
        self.verticalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CloseMinimizeButtons = QtWidgets.QFrame(parent=self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseMinimizeButtons.sizePolicy().hasHeightForWidth())
        self.CloseMinimizeButtons.setSizePolicy(sizePolicy)
        self.CloseMinimizeButtons.setStyleSheet("border:none;")
        self.CloseMinimizeButtons.setObjectName("CloseMinimizeButtons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.CloseMinimizeButtons)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimizeWindow_2 = QtWidgets.QPushButton(parent=self.CloseMinimizeButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizeWindow_2.sizePolicy().hasHeightForWidth())
        self.minimizeWindow_2.setSizePolicy(sizePolicy)
        self.minimizeWindow_2.setMinimumSize(QtCore.QSize(20, 20))
        self.minimizeWindow_2.setMaximumSize(QtCore.QSize(20, 20))
        self.minimizeWindow_2.setStyleSheet("border-radius:10px;")
        self.minimizeWindow_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/remove_24dp_EFEFEF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeWindow_2.setIcon(icon)
        self.minimizeWindow_2.setObjectName("minimizeWindow_2")
        self.horizontalLayout_4.addWidget(self.minimizeWindow_2)
        self.closeWindowButton_2 = QtWidgets.QPushButton(parent=self.CloseMinimizeButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeWindowButton_2.sizePolicy().hasHeightForWidth())
        self.closeWindowButton_2.setSizePolicy(sizePolicy)
        self.closeWindowButton_2.setMinimumSize(QtCore.QSize(20, 20))
        self.closeWindowButton_2.setMaximumSize(QtCore.QSize(20, 20))
        self.closeWindowButton_2.setStyleSheet("border-radius:10px;")
        self.closeWindowButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icon/close_24dp_EFEFEF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeWindowButton_2.setIcon(icon1)
        self.closeWindowButton_2.setObjectName("closeWindowButton_2")
        self.horizontalLayout_4.addWidget(self.closeWindowButton_2)
        self.verticalLayout_2.addWidget(self.CloseMinimizeButtons, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.AddFriendWrapper = QtWidgets.QFrame(parent=self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddFriendWrapper.sizePolicy().hasHeightForWidth())
        self.AddFriendWrapper.setSizePolicy(sizePolicy)
        self.AddFriendWrapper.setMaximumSize(QtCore.QSize(16777215, 200))
        self.AddFriendWrapper.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border:none;")
        self.AddFriendWrapper.setObjectName("AddFriendWrapper")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AddFriendWrapper)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.AddFriendWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color:white;\n"
"font-size:20px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FriendsNickPlaceholer = QtWidgets.QFrame(parent=self.AddFriendWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FriendsNickPlaceholer.sizePolicy().hasHeightForWidth())
        self.FriendsNickPlaceholer.setSizePolicy(sizePolicy)
        self.FriendsNickPlaceholer.setStyleSheet("background-color:rgba(38,40,45,255);")
        self.FriendsNickPlaceholer.setObjectName("FriendsNickPlaceholer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.FriendsNickPlaceholer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FriendsNick_input = QtWidgets.QLineEdit(parent=self.FriendsNickPlaceholer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FriendsNick_input.sizePolicy().hasHeightForWidth())
        self.FriendsNick_input.setSizePolicy(sizePolicy)
        self.FriendsNick_input.setMinimumSize(QtCore.QSize(250, 30))
        self.FriendsNick_input.setStyleSheet("QLineEdit {\n"
" width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#323338;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"}\n"
"\n"
"")
        self.FriendsNick_input.setObjectName("FriendsNick_input")
        self.horizontalLayout.addWidget(self.FriendsNick_input)
        self.AddFriend_button = QtWidgets.QPushButton(parent=self.FriendsNickPlaceholer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddFriend_button.sizePolicy().hasHeightForWidth())
        self.AddFriend_button.setSizePolicy(sizePolicy)
        self.AddFriend_button.setMinimumSize(QtCore.QSize(90, 35))
        self.AddFriend_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.AddFriend_button.setStyleSheet("border:3px solid white;\n"
"border-radius:10%;\n"
"color:white;\n"
"font-size:16px;")
        self.AddFriend_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI/icon/person_add_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.AddFriend_button.setIcon(icon2)
        self.AddFriend_button.setIconSize(QtCore.QSize(30, 30))
        self.AddFriend_button.setObjectName("AddFriend_button")
        self.horizontalLayout.addWidget(self.AddFriend_button)
        self.verticalLayout.addWidget(self.FriendsNickPlaceholer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Status = QtWidgets.QPushButton(parent=self.AddFriendWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status.sizePolicy().hasHeightForWidth())
        self.Status.setSizePolicy(sizePolicy)
        self.Status.setMinimumSize(QtCore.QSize(20, 20))
        self.Status.setText("")
        self.Status.setObjectName("Status")
        self.verticalLayout.addWidget(self.Status, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.AddFriendWrapper, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(AddFriend)
        QtCore.QMetaObject.connectSlotsByName(AddFriend)

    def retranslateUi(self, AddFriend):
        _translate = QtCore.QCoreApplication.translate
        AddFriend.setWindowTitle(_translate("AddFriend", "Dialog"))
        self.label.setText(_translate("AddFriend", "Введите никнейм друга"))
        self.FriendsNick_input.setPlaceholderText(_translate("AddFriend", "Ник друга..."))
