# Form implementation generated from reading ui file 'GroupInList.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupInList(object):
    def setupUi(self, GroupInList):
        GroupInList.setObjectName("GroupInList")
        GroupInList.resize(550, 235)
        self.Group_wrapper = QtWidgets.QFrame(parent=GroupInList)
        self.Group_wrapper.setGeometry(QtCore.QRect(30, 60, 501, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group_wrapper.sizePolicy().hasHeightForWidth())
        self.Group_wrapper.setSizePolicy(sizePolicy)
        self.Group_wrapper.setMinimumSize(QtCore.QSize(0, 80))
        self.Group_wrapper.setMaximumSize(QtCore.QSize(1000, 80))
        self.Group_wrapper.setStyleSheet("QFrame, QPushButton {\n"
"background-color:#323338;\n"
"border-radius:15%;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size:20px;\n"
"    color:white;\n"
"}")
        self.Group_wrapper.setObjectName("Group_wrapper")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Group_wrapper)
        self.horizontalLayout.setContentsMargins(-1, -1, 40, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GroupNickWrapp = QtWidgets.QFrame(parent=self.Group_wrapper)
        self.GroupNickWrapp.setObjectName("GroupNickWrapp")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.GroupNickWrapp)
        self.horizontalLayout_2.setContentsMargins(10, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GroupIcon = QtWidgets.QPushButton(parent=self.GroupNickWrapp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupIcon.sizePolicy().hasHeightForWidth())
        self.GroupIcon.setSizePolicy(sizePolicy)
        self.GroupIcon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.GroupIcon.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:25px;\n"
"color:White;\n"
"font-size:25px;\n"
"text-align:center;\n"
"")
        self.GroupIcon.setObjectName("GroupIcon")
        self.horizontalLayout_2.addWidget(self.GroupIcon)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.GroupNickWrapp)
        self.label.setStyleSheet("font-size:16px;\n"
"color:white;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.GroupName = QtWidgets.QLabel(parent=self.GroupNickWrapp)
        self.GroupName.setStyleSheet("font-size:16px;\n"
"color:white;")
        self.GroupName.setObjectName("GroupName")
        self.gridLayout.addWidget(self.GroupName, 0, 0, 1, 1)
        self.number_of_members = QtWidgets.QLabel(parent=self.GroupNickWrapp)
        self.number_of_members.setStyleSheet("font-size:16px;\n"
"color:white;")
        self.number_of_members.setObjectName("number_of_members")
        self.gridLayout.addWidget(self.number_of_members, 1, 1, 1, 1)
        self.has_password = QtWidgets.QPushButton(parent=self.GroupNickWrapp)
        self.has_password.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/icons8-password-16.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.has_password.setIcon(icon)
        self.has_password.setObjectName("has_password")
        self.gridLayout.addWidget(self.has_password, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.GroupNickWrapp)
        self.join_group = QtWidgets.QPushButton(parent=self.Group_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.join_group.sizePolicy().hasHeightForWidth())
        self.join_group.setSizePolicy(sizePolicy)
        self.join_group.setMinimumSize(QtCore.QSize(50, 50))
        self.join_group.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.join_group.setStyleSheet("border:none;")
        self.join_group.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icon/icons8-enter-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.join_group.setIcon(icon1)
        self.join_group.setIconSize(QtCore.QSize(40, 40))
        self.join_group.setObjectName("join_group")
        self.horizontalLayout.addWidget(self.join_group)
        self.horizontalLayout.setStretch(0, 3)

        self.retranslateUi(GroupInList)
        QtCore.QMetaObject.connectSlotsByName(GroupInList)

    def retranslateUi(self, GroupInList):
        _translate = QtCore.QCoreApplication.translate
        GroupInList.setWindowTitle(_translate("GroupInList", "Form"))
        self.GroupIcon.setText(_translate("GroupInList", "G"))
        self.label.setText(_translate("GroupInList", "Количество участников:"))
        self.GroupName.setText(_translate("GroupInList", "Имя пользователя"))
        self.number_of_members.setText(_translate("GroupInList", "0"))
