# Form implementation generated from reading ui file 'Registration.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(700, 750))
        Dialog.setMaximumSize(QtCore.QSize(700, 750))
        self.Wrapper = QtWidgets.QFrame(parent=Dialog)
        self.Wrapper.setGeometry(QtCore.QRect(-20, 0, 750, 750))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wrapper.sizePolicy().hasHeightForWidth())
        self.Wrapper.setSizePolicy(sizePolicy)
        self.Wrapper.setMinimumSize(QtCore.QSize(750, 750))
        self.Wrapper.setMaximumSize(QtCore.QSize(750, 750))
        self.Wrapper.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.Wrapper.setStatusTip("")
        self.Wrapper.setStyleSheet("background-color:#101317;\n"
"")
        self.Wrapper.setObjectName("Wrapper")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Wrapper)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Menu = QtWidgets.QFrame(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu.sizePolicy().hasHeightForWidth())
        self.Menu.setSizePolicy(sizePolicy)
        self.Menu.setMinimumSize(QtCore.QSize(600, 700))
        self.Menu.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border-radius:50px;")
        self.Menu.setObjectName("Menu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Menu)
        self.verticalLayout_8.setContentsMargins(-1, 20, -1, 20)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.WelcomeLay = QtWidgets.QFrame(parent=self.Menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WelcomeLay.sizePolicy().hasHeightForWidth())
        self.WelcomeLay.setSizePolicy(sizePolicy)
        self.WelcomeLay.setMinimumSize(QtCore.QSize(400, 100))
        self.WelcomeLay.setMaximumSize(QtCore.QSize(300, 100))
        self.WelcomeLay.setStyleSheet("")
        self.WelcomeLay.setObjectName("WelcomeLay")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.WelcomeLay)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(parent=self.WelcomeLay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("text-align:center;\n"
"color:white;\n"
"font-size:26px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_8.addWidget(self.WelcomeLay, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.Namer = QtWidgets.QFrame(parent=self.Menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Namer.sizePolicy().hasHeightForWidth())
        self.Namer.setSizePolicy(sizePolicy)
        self.Namer.setMinimumSize(QtCore.QSize(500, 100))
        self.Namer.setObjectName("Namer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Namer)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(parent=self.Namer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.Name_input = QtWidgets.QLineEdit(parent=self.Namer)
        self.Name_input.setMinimumSize(QtCore.QSize(250, 0))
        self.Name_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.Name_input.setText("")
        self.Name_input.setObjectName("Name_input")
        self.verticalLayout_10.addWidget(self.Name_input)
        self.verticalLayout_8.addWidget(self.Namer, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.login = QtWidgets.QFrame(parent=self.Menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setMinimumSize(QtCore.QSize(500, 100))
        self.login.setObjectName("login")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.login)
        self.verticalLayout_11.setContentsMargins(10, 1, 10, 1)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(parent=self.login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.login_input = QtWidgets.QLineEdit(parent=self.login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_input.sizePolicy().hasHeightForWidth())
        self.login_input.setSizePolicy(sizePolicy)
        self.login_input.setMinimumSize(QtCore.QSize(250, 0))
        self.login_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.login_input.setObjectName("login_input")
        self.verticalLayout_11.addWidget(self.login_input)
        self.verticalLayout_8.addWidget(self.login, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.PasswordCreation = QtWidgets.QFrame(parent=self.Menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswordCreation.sizePolicy().hasHeightForWidth())
        self.PasswordCreation.setSizePolicy(sizePolicy)
        self.PasswordCreation.setMinimumSize(QtCore.QSize(500, 100))
        self.PasswordCreation.setObjectName("PasswordCreation")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.PasswordCreation)
        self.verticalLayout_13.setContentsMargins(10, 1, 10, 1)
        self.verticalLayout_13.setSpacing(1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(parent=self.PasswordCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.Password_input_ = QtWidgets.QLineEdit(parent=self.PasswordCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Password_input_.sizePolicy().hasHeightForWidth())
        self.Password_input_.setSizePolicy(sizePolicy)
        self.Password_input_.setMinimumSize(QtCore.QSize(250, 0))
        self.Password_input_.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.Password_input_.setObjectName("Password_input_")
        self.verticalLayout_13.addWidget(self.Password_input_)
        self.verticalLayout_8.addWidget(self.PasswordCreation, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Registr = QtWidgets.QFrame(parent=self.Menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Registr.sizePolicy().hasHeightForWidth())
        self.Registr.setSizePolicy(sizePolicy)
        self.Registr.setMinimumSize(QtCore.QSize(500, 100))
        self.Registr.setObjectName("Registr")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Registr)
        self.verticalLayout_12.setContentsMargins(10, 1, 10, 1)
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.RegistrationButton = QtWidgets.QPushButton(parent=self.Registr)
        self.RegistrationButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.RegistrationButton.setStyleSheet("QPushButton {\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#323338;\n"
"font-size:16px;\n"
"color:#808994;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#656c76;\n"
"color:black;\n"
"}")
        self.RegistrationButton.setObjectName("RegistrationButton")
        self.verticalLayout_12.addWidget(self.RegistrationButton)
        self.verticalLayout_8.addWidget(self.Registr, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HadAccount = QtWidgets.QFrame(parent=self.Menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HadAccount.sizePolicy().hasHeightForWidth())
        self.HadAccount.setSizePolicy(sizePolicy)
        self.HadAccount.setMinimumSize(QtCore.QSize(300, 40))
        self.HadAccount.setStyleSheet("color:white;")
        self.HadAccount.setObjectName("HadAccount")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.HadAccount)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SignInFromRegistrationButton = QtWidgets.QPushButton(parent=self.HadAccount)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignInFromRegistrationButton.sizePolicy().hasHeightForWidth())
        self.SignInFromRegistrationButton.setSizePolicy(sizePolicy)
        self.SignInFromRegistrationButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SignInFromRegistrationButton.setStyleSheet("font-size:18px;")
        self.SignInFromRegistrationButton.setObjectName("SignInFromRegistrationButton")
        self.horizontalLayout_3.addWidget(self.SignInFromRegistrationButton)
        self.verticalLayout_8.addWidget(self.HadAccount, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_3.addWidget(self.Menu, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "Создайте учетную запись"))
        self.label_7.setText(_translate("Dialog", "Ваше имя"))
        self.label_8.setText(_translate("Dialog", "Логин"))
        self.label_9.setText(_translate("Dialog", "Пароль"))
        self.RegistrationButton.setText(_translate("Dialog", "Создать аккаунт"))
        self.SignInFromRegistrationButton.setText(_translate("Dialog", "Уже зарегестрирован?"))
