# Form implementation generated from reading ui file 'GroupRequest.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupRequest(object):
    def setupUi(self, GroupRequest):
        GroupRequest.setObjectName("GroupRequest")
        GroupRequest.resize(550, 300)
        self.Group_wrapper = QtWidgets.QFrame(parent=GroupRequest)
        self.Group_wrapper.setGeometry(QtCore.QRect(30, 60, 501, 80))
        self.Group_wrapper.setMinimumSize(QtCore.QSize(0, 80))
        self.Group_wrapper.setMaximumSize(QtCore.QSize(1000, 80))
        self.Group_wrapper.setStyleSheet("QFrame, QPushButton {\n"
"background-color:#323338;\n"
"border-radius:15%;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size:20px;\n"
"    color:white;\n"
"}")
        self.Group_wrapper.setObjectName("Group_wrapper")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Group_wrapper)
        self.horizontalLayout.setContentsMargins(-1, -1, 40, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GroupNickWrapp = QtWidgets.QFrame(parent=self.Group_wrapper)
        self.GroupNickWrapp.setObjectName("GroupNickWrapp")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.GroupNickWrapp)
        self.horizontalLayout_2.setContentsMargins(10, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GroupIcon = QtWidgets.QPushButton(parent=self.GroupNickWrapp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupIcon.sizePolicy().hasHeightForWidth())
        self.GroupIcon.setSizePolicy(sizePolicy)
        self.GroupIcon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.GroupIcon.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:25px;\n"
"color:White;\n"
"font-size:25px;\n"
"text-align:center;\n"
"")
        self.GroupIcon.setObjectName("GroupIcon")
        self.horizontalLayout_2.addWidget(self.GroupIcon)
        self.GroupName = QtWidgets.QLabel(parent=self.GroupNickWrapp)
        self.GroupName.setStyleSheet("font-size:20px;\n"
"color:white;")
        self.GroupName.setObjectName("GroupName")
        self.horizontalLayout_2.addWidget(self.GroupName)
        self.horizontalLayout.addWidget(self.GroupNickWrapp)
        self.accept_request = QtWidgets.QPushButton(parent=self.Group_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accept_request.sizePolicy().hasHeightForWidth())
        self.accept_request.setSizePolicy(sizePolicy)
        self.accept_request.setMinimumSize(QtCore.QSize(50, 50))
        self.accept_request.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.accept_request.setStyleSheet("border:none;")
        self.accept_request.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/person_add_46dp_018741_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.accept_request.setIcon(icon)
        self.accept_request.setIconSize(QtCore.QSize(40, 40))
        self.accept_request.setObjectName("accept_request")
        self.horizontalLayout.addWidget(self.accept_request)
        self.decline_request = QtWidgets.QPushButton(parent=self.Group_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decline_request.sizePolicy().hasHeightForWidth())
        self.decline_request.setSizePolicy(sizePolicy)
        self.decline_request.setMinimumSize(QtCore.QSize(50, 50))
        self.decline_request.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.decline_request.setStyleSheet("border:none;")
        self.decline_request.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icon/person_cancel_46dp_8B1A10_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.decline_request.setIcon(icon1)
        self.decline_request.setIconSize(QtCore.QSize(40, 40))
        self.decline_request.setObjectName("decline_request")
        self.horizontalLayout.addWidget(self.decline_request)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(GroupRequest)
        QtCore.QMetaObject.connectSlotsByName(GroupRequest)

    def retranslateUi(self, GroupRequest):
        _translate = QtCore.QCoreApplication.translate
        GroupRequest.setWindowTitle(_translate("GroupRequest", "Form"))
        self.GroupIcon.setText(_translate("GroupRequest", "G"))
        self.GroupName.setText(_translate("GroupRequest", "Имя пользователя"))
