# Form implementation generated from reading ui file 'Call.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Call(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 517)
        self.WrapperForProfile = QtWidgets.QFrame(parent=Form)
        self.WrapperForProfile.setGeometry(QtCore.QRect(40, 80, 230, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WrapperForProfile.sizePolicy().hasHeightForWidth())
        self.WrapperForProfile.setSizePolicy(sizePolicy)
        self.WrapperForProfile.setMinimumSize(QtCore.QSize(230, 280))
        self.WrapperForProfile.setMaximumSize(QtCore.QSize(230, 280))
        self.WrapperForProfile.setStyleSheet("QFrame {\n"
"background-color:rgba(16,19,23,255);\n"
"border:4px solid white;\n"
"border-radius:15%;\n"
"}")
        self.WrapperForProfile.setObjectName("WrapperForProfile")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.WrapperForProfile)
        self.verticalLayout_2.setContentsMargins(11, 0, 11, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LogoField = QtWidgets.QFrame(parent=self.WrapperForProfile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoField.sizePolicy().hasHeightForWidth())
        self.LogoField.setSizePolicy(sizePolicy)
        self.LogoField.setMinimumSize(QtCore.QSize(0, 100))
        self.LogoField.setStyleSheet("QFrame {\n"
" border:none;\n"
"}")
        self.LogoField.setObjectName("LogoField")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.LogoField)
        self.horizontalLayout_4.setContentsMargins(10, 11, 10, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(parent=self.LogoField)
        self.widget.setMinimumSize(QtCore.QSize(0, 70))
        self.widget.setMaximumSize(QtCore.QSize(75, 75))
        self.widget.setStyleSheet("background-color:none;")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QPushButton(parent=self.widget)
        self.logo.setGeometry(QtCore.QRect(0, 0, 75, 75))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(75, 75))
        self.logo.setMaximumSize(QtCore.QSize(60, 65))
        self.logo.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:37%;\n"
"color:White;\n"
"font-size:32px;\n"
"")
        self.logo.setObjectName("logo")
        self.horizontalLayout_4.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.LogoField)
        self.LogoStatusNickname = QtWidgets.QFrame(parent=self.WrapperForProfile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoStatusNickname.sizePolicy().hasHeightForWidth())
        self.LogoStatusNickname.setSizePolicy(sizePolicy)
        self.LogoStatusNickname.setStyleSheet("border:none;")
        self.LogoStatusNickname.setObjectName("LogoStatusNickname")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.LogoStatusNickname)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.NickName = QtWidgets.QLabel(parent=self.LogoStatusNickname)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NickName.sizePolicy().hasHeightForWidth())
        self.NickName.setSizePolicy(sizePolicy)
        self.NickName.setStyleSheet("font-size:26px;\n"
"color:white;\n"
"border:none;")
        self.NickName.setWordWrap(True)
        self.NickName.setObjectName("NickName")
        self.verticalLayout_4.addWidget(self.NickName, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addWidget(self.LogoStatusNickname)
        self.buttonsArea = QtWidgets.QFrame(parent=self.WrapperForProfile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonsArea.sizePolicy().hasHeightForWidth())
        self.buttonsArea.setSizePolicy(sizePolicy)
        self.buttonsArea.setStyleSheet("border:0;")
        self.buttonsArea.setObjectName("buttonsArea")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonsArea)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AcceptCall_button = QtWidgets.QPushButton(parent=self.buttonsArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AcceptCall_button.sizePolicy().hasHeightForWidth())
        self.AcceptCall_button.setSizePolicy(sizePolicy)
        self.AcceptCall_button.setMinimumSize(QtCore.QSize(60, 60))
        self.AcceptCall_button.setMaximumSize(QtCore.QSize(40, 40))
        self.AcceptCall_button.setStyleSheet("border-color:green;\n"
"background-color:green;\n"
"border-radius:30%;")
        self.AcceptCall_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/call_28dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.AcceptCall_button.setIcon(icon)
        self.AcceptCall_button.setIconSize(QtCore.QSize(28, 28))
        self.AcceptCall_button.setObjectName("AcceptCall_button")
        self.horizontalLayout.addWidget(self.AcceptCall_button, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.DeclineCall_button = QtWidgets.QPushButton(parent=self.buttonsArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeclineCall_button.sizePolicy().hasHeightForWidth())
        self.DeclineCall_button.setSizePolicy(sizePolicy)
        self.DeclineCall_button.setMinimumSize(QtCore.QSize(60, 60))
        self.DeclineCall_button.setMaximumSize(QtCore.QSize(40, 40))
        self.DeclineCall_button.setStyleSheet("border-color:#BB271A;\n"
"background-color:#BB271A;\n"
"border-radius:30%;")
        self.DeclineCall_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icon/call_end_28dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.DeclineCall_button.setIcon(icon1)
        self.DeclineCall_button.setIconSize(QtCore.QSize(28, 28))
        self.DeclineCall_button.setObjectName("DeclineCall_button")
        self.horizontalLayout.addWidget(self.DeclineCall_button, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.buttonsArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.logo.setText(_translate("Form", "U"))
        self.NickName.setText(_translate("Form", "User"))