# Form implementation generated from reading ui file 'Group.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Group(object):
    def setupUi(self, Group):
        Group.setObjectName("Group")
        Group.resize(747, 664)
        self.MAIN = QtWidgets.QFrame(parent=Group)
        self.MAIN.setGeometry(QtCore.QRect(-10, -10, 761, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MAIN.sizePolicy().hasHeightForWidth())
        self.MAIN.setSizePolicy(sizePolicy)
        self.MAIN.setObjectName("MAIN")
        self.MAIN_ChatLayout = QtWidgets.QHBoxLayout(self.MAIN)
        self.MAIN_ChatLayout.setContentsMargins(-1, -1, -1, 0)
        self.MAIN_ChatLayout.setSpacing(0)
        self.MAIN_ChatLayout.setObjectName("MAIN_ChatLayout")
        self.Column = QtWidgets.QFrame(parent=self.MAIN)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Column.sizePolicy().hasHeightForWidth())
        self.Column.setSizePolicy(sizePolicy)
        self.Column.setMinimumSize(QtCore.QSize(50, 50))
        self.Column.setStyleSheet("background-color:rgba(16,19,23,255);")
        self.Column.setObjectName("Column")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Column)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TopBar_2 = QtWidgets.QFrame(parent=self.Column)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopBar_2.sizePolicy().hasHeightForWidth())
        self.TopBar_2.setSizePolicy(sizePolicy)
        self.TopBar_2.setMinimumSize(QtCore.QSize(0, 100))
        self.TopBar_2.setStyleSheet("background-color:rgba(34,35,39,255);")
        self.TopBar_2.setObjectName("TopBar_2")
        self.TopBar = QtWidgets.QHBoxLayout(self.TopBar_2)
        self.TopBar.setContentsMargins(35, -1, 35, -1)
        self.TopBar.setObjectName("TopBar")
        self.verticalFrame = QtWidgets.QFrame(parent=self.TopBar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UserIconAndNickInChat_2 = QtWidgets.QFrame(parent=self.verticalFrame)
        self.UserIconAndNickInChat_2.setObjectName("UserIconAndNickInChat_2")
        self.LogoAndNickName_2 = QtWidgets.QHBoxLayout(self.UserIconAndNickInChat_2)
        self.LogoAndNickName_2.setContentsMargins(-1, -1, -1, 5)
        self.LogoAndNickName_2.setSpacing(15)
        self.LogoAndNickName_2.setObjectName("LogoAndNickName_2")
        self.GroupIcon = QtWidgets.QPushButton(parent=self.UserIconAndNickInChat_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupIcon.sizePolicy().hasHeightForWidth())
        self.GroupIcon.setSizePolicy(sizePolicy)
        self.GroupIcon.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.GroupIcon.setStyleSheet("background-color:purple;\n"
"width:50px;\n"
"height:50px;\n"
"border-radius:25px;\n"
"color:White;\n"
"font-size:25px;\n"
"text-align:center;\n"
"")
        self.GroupIcon.setObjectName("GroupIcon")
        self.LogoAndNickName_2.addWidget(self.GroupIcon)
        self.GroupName = QtWidgets.QPushButton(parent=self.UserIconAndNickInChat_2)
        self.GroupName.setMinimumSize(QtCore.QSize(135, 0))
        self.GroupName.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.GroupName.setStyleSheet("QPushButton {\n"
"    font-size:26px;\n"
"    color:white;\n"
"    border:none;\n"
"    padding:5px;\n"
"    padding-left:10px;\n"
"    padding-right:30px;\n"
"    border-radius:15%;\n"
"    text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 40);\n"
"    background-image:url(GUI/icon/icons8-редактировать-25.png);\n"
"    background-position:right; \n"
"    background-repeat:no-repeat;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background: rgba(255, 255, 255, 90);\n"
"    background-image:url(GUI/icon/icons8-редактировать-25.png);\n"
"    background-position:right; \n"
"    background-repeat:no-repeat;\n"
"}\n"
"")
        self.GroupName.setObjectName("GroupName")
        self.LogoAndNickName_2.addWidget(self.GroupName)
        self.verticalLayout_3.addWidget(self.UserIconAndNickInChat_2)
        self.horizontalFrame = QtWidgets.QFrame(parent=self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setContentsMargins(15, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.members_number = QtWidgets.QPushButton(parent=self.horizontalFrame)
        self.members_number.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.members_number.setStyleSheet("font-size:16px;\n"
"color:grey;\n"
"border:none;")
        self.members_number.setObjectName("members_number")
        self.horizontalLayout_2.addWidget(self.members_number)
        self.online_members_number = QtWidgets.QLabel(parent=self.horizontalFrame)
        self.online_members_number.setStyleSheet("font-size:16px;\n"
"color:grey;")
        self.online_members_number.setObjectName("online_members_number")
        self.horizontalLayout_2.addWidget(self.online_members_number)
        self.verticalLayout_3.addWidget(self.horizontalFrame)
        self.TopBar.addWidget(self.verticalFrame)
        self.horizontalFrame_2 = QtWidgets.QFrame(parent=self.TopBar_2)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(90, 50))
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.miniIconsCall = QtWidgets.QHBoxLayout()
        self.miniIconsCall.setObjectName("miniIconsCall")
        self.horizontalLayout.addLayout(self.miniIconsCall)
        self.TopBar.addWidget(self.horizontalFrame_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.CallAndInfoButtons = QtWidgets.QFrame(parent=self.TopBar_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CallAndInfoButtons.sizePolicy().hasHeightForWidth())
        self.CallAndInfoButtons.setSizePolicy(sizePolicy)
        self.CallAndInfoButtons.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius:15%;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background: rgba(255, 255, 255, 90);\n"
"}")
        self.CallAndInfoButtons.setObjectName("CallAndInfoButtons")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CallAndInfoButtons)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CallButton = QtWidgets.QPushButton(parent=self.CallAndInfoButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CallButton.sizePolicy().hasHeightForWidth())
        self.CallButton.setSizePolicy(sizePolicy)
        self.CallButton.setMinimumSize(QtCore.QSize(45, 45))
        self.CallButton.setMaximumSize(QtCore.QSize(40, 40))
        self.CallButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.CallButton.setStyleSheet("")
        self.CallButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/call_46dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.CallButton.setIcon(icon)
        self.CallButton.setIconSize(QtCore.QSize(30, 30))
        self.CallButton.setObjectName("CallButton")
        self.horizontalLayout_5.addWidget(self.CallButton)
        self.invite_user = QtWidgets.QPushButton(parent=self.CallAndInfoButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invite_user.sizePolicy().hasHeightForWidth())
        self.invite_user.setSizePolicy(sizePolicy)
        self.invite_user.setMinimumSize(QtCore.QSize(45, 45))
        self.invite_user.setMaximumSize(QtCore.QSize(40, 40))
        self.invite_user.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.invite_user.setStyleSheet("")
        self.invite_user.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icon/icons8-add-male-user-group-46.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.invite_user.setIcon(icon1)
        self.invite_user.setIconSize(QtCore.QSize(30, 30))
        self.invite_user.setObjectName("invite_user")
        self.horizontalLayout_5.addWidget(self.invite_user)
        self.show_members = QtWidgets.QPushButton(parent=self.CallAndInfoButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_members.sizePolicy().hasHeightForWidth())
        self.show_members.setSizePolicy(sizePolicy)
        self.show_members.setMinimumSize(QtCore.QSize(45, 45))
        self.show_members.setMaximumSize(QtCore.QSize(40, 40))
        self.show_members.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.show_members.setStyleSheet("")
        self.show_members.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI/icon/icons8-группы-пользователей-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.show_members.setIcon(icon2)
        self.show_members.setIconSize(QtCore.QSize(30, 30))
        self.show_members.setObjectName("show_members")
        self.horizontalLayout_5.addWidget(self.show_members)
        self.TopBar.addWidget(self.CallAndInfoButtons)
        self.verticalLayout_2.addWidget(self.TopBar_2)
        self.UnderBarLayout = QtWidgets.QFrame(parent=self.Column)
        self.UnderBarLayout.setObjectName("UnderBarLayout")
        self._2 = QtWidgets.QHBoxLayout(self.UnderBarLayout)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.ChatLayout = QtWidgets.QFrame(parent=self.UnderBarLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatLayout.sizePolicy().hasHeightForWidth())
        self.ChatLayout.setSizePolicy(sizePolicy)
        self.ChatLayout.setMinimumSize(QtCore.QSize(0, 0))
        self.ChatLayout.setObjectName("ChatLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ChatLayout)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Call = QtWidgets.QFrame(parent=self.ChatLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Call.sizePolicy().hasHeightForWidth())
        self.Call.setSizePolicy(sizePolicy)
        self.Call.setMinimumSize(QtCore.QSize(0, 200))
        self.Call.setStyleSheet("QFrame{\n"
"background-color:rgba(38,40,45,255);\n"
"border-top:3px solid white;\n"
"border-bottom:3px solid white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border:3px solid white;\n"
"    border-radius:50%;\n"
"    color:white;\n"
"    font-size:30px;\n"
"}")
        self.Call.setObjectName("Call")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Call)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UsersFiled_layout = QtWidgets.QHBoxLayout()
        self.UsersFiled_layout.setSpacing(0)
        self.UsersFiled_layout.setObjectName("UsersFiled_layout")
        self.verticalLayout.addLayout(self.UsersFiled_layout)
        self.horizontalFrame1 = QtWidgets.QFrame(parent=self.Call)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame1.sizePolicy().hasHeightForWidth())
        self.horizontalFrame1.setSizePolicy(sizePolicy)
        self.horizontalFrame1.setStyleSheet("QFrame {\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border:3px solid orange;\n"
"    border-radius:15%;\n"
"    color:white;\n"
"    font-size:30px;\n"
"}")
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.wrapperForButtons = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.wrapperForButtons.setSpacing(25)
        self.wrapperForButtons.setObjectName("wrapperForButtons")
        self.videoCall = QtWidgets.QPushButton(parent=self.horizontalFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoCall.sizePolicy().hasHeightForWidth())
        self.videoCall.setSizePolicy(sizePolicy)
        self.videoCall.setMinimumSize(QtCore.QSize(40, 40))
        self.videoCall.setMaximumSize(QtCore.QSize(40, 40))
        self.videoCall.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.videoCall.setStyleSheet("QPushButton {\n"
"    border:2px solid white;\n"
"    background-color:black;\n"
"}\n"
"QPushButton:checked {\n"
"    border: 2px solid #e6a23c;\n"
"    background-color: red;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(229, 229, 229, 55);\n"
"}\n"
"QPushButton:checked:hover {\n"
"    background-color: red;\n"
"}")
        self.videoCall.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../.designer/icon/videocam_28dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.videoCall.setIcon(icon3)
        self.videoCall.setIconSize(QtCore.QSize(28, 28))
        self.videoCall.setCheckable(True)
        self.videoCall.setObjectName("videoCall")
        self.wrapperForButtons.addWidget(self.videoCall)
        self.muteMic = QtWidgets.QPushButton(parent=self.horizontalFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.muteMic.sizePolicy().hasHeightForWidth())
        self.muteMic.setSizePolicy(sizePolicy)
        self.muteMic.setMinimumSize(QtCore.QSize(40, 40))
        self.muteMic.setMaximumSize(QtCore.QSize(40, 40))
        self.muteMic.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.muteMic.setStyleSheet("QPushButton {\n"
"    border:2px solid white;\n"
"    background-color:black;\n"
"}\n"
"QPushButton:checked {\n"
"    border: 2px solid #e6a23c;\n"
"    background-color: red;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(229, 229, 229, 55);\n"
"}\n"
"QPushButton:checked:hover {\n"
"    background-color: red;\n"
"}")
        self.muteMic.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("GUI/icon/mic_off_28dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.muteMic.setIcon(icon4)
        self.muteMic.setIconSize(QtCore.QSize(28, 28))
        self.muteMic.setCheckable(True)
        self.muteMic.setObjectName("muteMic")
        self.wrapperForButtons.addWidget(self.muteMic)
        self.muteHeadphones = QtWidgets.QPushButton(parent=self.horizontalFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.muteHeadphones.sizePolicy().hasHeightForWidth())
        self.muteHeadphones.setSizePolicy(sizePolicy)
        self.muteHeadphones.setMinimumSize(QtCore.QSize(40, 40))
        self.muteHeadphones.setMaximumSize(QtCore.QSize(40, 40))
        self.muteHeadphones.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.muteHeadphones.setStyleSheet("QPushButton {\n"
"    border:2px solid white;\n"
"    background-color:black;\n"
"}\n"
"QPushButton:checked {\n"
"    border: 2px solid #e6a23c;\n"
"    background-color: red;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(229, 229, 229, 55);\n"
"}\n"
"QPushButton:checked:hover {\n"
"    background-color: red;\n"
"}")
        self.muteHeadphones.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("GUI/icon/headset_off_28dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.muteHeadphones.setIcon(icon5)
        self.muteHeadphones.setIconSize(QtCore.QSize(28, 28))
        self.muteHeadphones.setCheckable(True)
        self.muteHeadphones.setFlat(False)
        self.muteHeadphones.setObjectName("muteHeadphones")
        self.wrapperForButtons.addWidget(self.muteHeadphones)
        self.leaveCall = QtWidgets.QPushButton(parent=self.horizontalFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leaveCall.sizePolicy().hasHeightForWidth())
        self.leaveCall.setSizePolicy(sizePolicy)
        self.leaveCall.setMinimumSize(QtCore.QSize(40, 40))
        self.leaveCall.setMaximumSize(QtCore.QSize(40, 40))
        self.leaveCall.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.leaveCall.setStyleSheet("border-color:#BB271A;\n"
"background-color:#BB271A;")
        self.leaveCall.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("GUI/icon/call_end_28dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.leaveCall.setIcon(icon6)
        self.leaveCall.setIconSize(QtCore.QSize(28, 28))
        self.leaveCall.setObjectName("leaveCall")
        self.wrapperForButtons.addWidget(self.leaveCall, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout.addWidget(self.horizontalFrame1, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_7.addWidget(self.Call)
        self.MessahesInChat = QtWidgets.QFrame(parent=self.ChatLayout)
        self.MessahesInChat.setObjectName("MessahesInChat")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.MessahesInChat)
        self.verticalLayout_5.setContentsMargins(45, -1, 45, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ChatScroll = QtWidgets.QListWidget(parent=self.MessahesInChat)
        self.ChatScroll.setStyleSheet("QListWidget {\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"QListWidget::item\n"
"{\n"
"    background:none; \n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"           border:none;\n"
"            width:10px;\n"
"             height:20px;\n"
"                                                            \n"
"  }\n"
"                                                        \n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"         heigth:0;\n"
" }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"               background: none;\n"
" }\n"
"  QScrollBar::add-line:vertical {\n"
"               height: 0px;\n"
"  }\n"
" QScrollBar::sub-line:vertical {\n"
"                 height: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {\n"
"               background: orange;\n"
"                min-height:10px;\n"
"                 border-radius: 5px;\n"
" }")
        self.ChatScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.ChatScroll.setObjectName("ChatScroll")
        self.verticalLayout_5.addWidget(self.ChatScroll)
        self.verticalLayout_7.addWidget(self.MessahesInChat)
        self.ChatInputLayout = QtWidgets.QFrame(parent=self.ChatLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChatInputLayout.sizePolicy().hasHeightForWidth())
        self.ChatInputLayout.setSizePolicy(sizePolicy)
        self.ChatInputLayout.setObjectName("ChatInputLayout")
        self.Chat_input = QtWidgets.QHBoxLayout(self.ChatInputLayout)
        self.Chat_input.setContentsMargins(-1, -1, -1, 20)
        self.Chat_input.setSpacing(7)
        self.Chat_input.setObjectName("Chat_input")
        self.Chat_input_ = QtWidgets.QLineEdit(parent=self.ChatInputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Chat_input_.sizePolicy().hasHeightForWidth())
        self.Chat_input_.setSizePolicy(sizePolicy)
        self.Chat_input_.setMinimumSize(QtCore.QSize(200, 0))
        self.Chat_input_.setStyleSheet("QLineEdit {\n"
" width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius:20%;\n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"background-color:#323338;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#656c76;\n"
"color:black;\n"
"background-image: url(GUI/icon/search_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg); \n"
"background-repeat: no-repeat;\n"
"background-position: left;\n"
"}")
        self.Chat_input_.setText("")
        self.Chat_input_.setObjectName("Chat_input_")
        self.Chat_input.addWidget(self.Chat_input_)
        self.Attcahment_button = QtWidgets.QPushButton(parent=self.ChatInputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Attcahment_button.sizePolicy().hasHeightForWidth())
        self.Attcahment_button.setSizePolicy(sizePolicy)
        self.Attcahment_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Attcahment_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Attcahment_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Attcahment_button.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border-radius:25%;\n"
"border:3px solid white;")
        self.Attcahment_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("GUI/icon/attach_file_46dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Attcahment_button.setIcon(icon7)
        self.Attcahment_button.setIconSize(QtCore.QSize(30, 30))
        self.Attcahment_button.setObjectName("Attcahment_button")
        self.Chat_input.addWidget(self.Attcahment_button)
        self.Send_button = QtWidgets.QPushButton(parent=self.ChatInputLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send_button.sizePolicy().hasHeightForWidth())
        self.Send_button.setSizePolicy(sizePolicy)
        self.Send_button.setMinimumSize(QtCore.QSize(50, 50))
        self.Send_button.setMaximumSize(QtCore.QSize(50, 50))
        self.Send_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Send_button.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border-radius:25%;\n"
"border:3px solid white;")
        self.Send_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("GUI/icon/send_30dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Send_button.setIcon(icon8)
        self.Send_button.setIconSize(QtCore.QSize(30, 30))
        self.Send_button.setObjectName("Send_button")
        self.Chat_input.addWidget(self.Send_button)
        self.verticalLayout_7.addWidget(self.ChatInputLayout)
        self._2.addWidget(self.ChatLayout)
        self.members_column = QtWidgets.QFrame(parent=self.UnderBarLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.members_column.sizePolicy().hasHeightForWidth())
        self.members_column.setSizePolicy(sizePolicy)
        self.members_column.setMinimumSize(QtCore.QSize(250, 0))
        self.members_column.setStyleSheet("QFrame{\n"
"background-color:rgba(38,40,45,255);\n"
"border-left:3px solid white;\n"
"}")
        self.members_column.setObjectName("members_column")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.members_column)
        self.verticalLayout_6.setContentsMargins(10, 0, 0, 25)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.members_list = QtWidgets.QListWidget(parent=self.members_column)
        self.members_list.setStyleSheet("border:none;")
        self.members_list.setObjectName("members_list")
        self.verticalLayout_6.addWidget(self.members_list)
        self.leave_group = QtWidgets.QPushButton(parent=self.members_column)
        self.leave_group.setMinimumSize(QtCore.QSize(0, 64))
        self.leave_group.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.leave_group.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.leave_group.setStyleSheet("QPushButton {\n"
"    background-color:none;\n"
"    border:none;\n"
"    font-size:18px;\n"
"    color:#BB271A;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("GUI/icon/icons8-выход-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.leave_group.setIcon(icon9)
        self.leave_group.setIconSize(QtCore.QSize(52, 52))
        self.leave_group.setObjectName("leave_group")
        self.verticalLayout_6.addWidget(self.leave_group)
        self._2.addWidget(self.members_column)
        self.verticalLayout_2.addWidget(self.UnderBarLayout)
        self.MAIN_ChatLayout.addWidget(self.Column)

        self.retranslateUi(Group)
        QtCore.QMetaObject.connectSlotsByName(Group)

    def retranslateUi(self, Group):
        _translate = QtCore.QCoreApplication.translate
        Group.setWindowTitle(_translate("Group", "Form"))
        self.GroupIcon.setText(_translate("Group", "G"))
        self.GroupName.setText(_translate("Group", "Group-1"))
        self.members_number.setText(_translate("Group", "N участников,"))
        self.online_members_number.setText(_translate("Group", "N в сети"))
        self.Chat_input_.setPlaceholderText(_translate("Group", "Введите сообщение"))
        self.leave_group.setText(_translate("Group", "Покинуть группу"))
