# Form implementation generated from reading ui file 'group_member.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(542, 136)
        Form.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.member_wrapper = QtWidgets.QFrame(parent=Form)
        self.member_wrapper.setGeometry(QtCore.QRect(30, 30, 221, 60))
        self.member_wrapper.setMinimumSize(QtCore.QSize(0, 60))
        self.member_wrapper.setMaximumSize(QtCore.QSize(1000, 60))
        self.member_wrapper.setStyleSheet("")
        self.member_wrapper.setObjectName("member_wrapper")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.member_wrapper)
        self.horizontalLayout.setContentsMargins(0, 0, 25, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GroupNickWrapp = QtWidgets.QFrame(parent=self.member_wrapper)
        self.GroupNickWrapp.setObjectName("GroupNickWrapp")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.GroupNickWrapp)
        self.horizontalLayout_2.setContentsMargins(10, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wrapp = QtWidgets.QWidget(parent=self.GroupNickWrapp)
        self.wrapp.setMaximumSize(QtCore.QSize(30, 30))
        self.wrapp.setStyleSheet("QWidget {\n"
"background:none;\n"
"}")
        self.wrapp.setObjectName("wrapp")
        self.user_logo = QtWidgets.QPushButton(parent=self.wrapp)
        self.user_logo.setGeometry(QtCore.QRect(0, 0, 30, 30))
        self.user_logo.setMaximumSize(QtCore.QSize(40, 40))
        self.user_logo.setStyleSheet("background-color:purple;\n"
"border-radius:13%;\n"
"font-size:14px;\n"
"color:white;")
        self.user_logo.setText("")
        self.user_logo.setObjectName("user_logo")
        self.ActivityIndicator_chatList = QtWidgets.QPushButton(parent=self.wrapp)
        self.ActivityIndicator_chatList.setGeometry(QtCore.QRect(20, 20, 10, 10))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ActivityIndicator_chatList.sizePolicy().hasHeightForWidth())
        self.ActivityIndicator_chatList.setSizePolicy(sizePolicy)
        self.ActivityIndicator_chatList.setMinimumSize(QtCore.QSize(10, 10))
        self.ActivityIndicator_chatList.setMaximumSize(QtCore.QSize(10, 10))
        self.ActivityIndicator_chatList.setStyleSheet("background-color:green;\n"
"border-radius:5%;\n"
"color:White;\n"
"\n"
"")
        self.ActivityIndicator_chatList.setText("")
        self.ActivityIndicator_chatList.setObjectName("ActivityIndicator_chatList")
        self.horizontalLayout_2.addWidget(self.wrapp)
        self.nick_name = QtWidgets.QLabel(parent=self.GroupNickWrapp)
        self.nick_name.setStyleSheet("font-size:12px;\n"
"color:white;")
        self.nick_name.setObjectName("nick_name")
        self.horizontalLayout_2.addWidget(self.nick_name)
        self.horizontalLayout.addWidget(self.GroupNickWrapp)
        self.is_admin = QtWidgets.QPushButton(parent=self.member_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_admin.sizePolicy().hasHeightForWidth())
        self.is_admin.setSizePolicy(sizePolicy)
        self.is_admin.setMinimumSize(QtCore.QSize(25, 25))
        self.is_admin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.is_admin.setStyleSheet("border:none;\n"
"background-color:transparent;")
        self.is_admin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/icon/icons8-star-20.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.is_admin.setIcon(icon)
        self.is_admin.setIconSize(QtCore.QSize(20, 20))
        self.is_admin.setObjectName("is_admin")
        self.horizontalLayout.addWidget(self.is_admin, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.kick_user = QtWidgets.QPushButton(parent=self.member_wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kick_user.sizePolicy().hasHeightForWidth())
        self.kick_user.setSizePolicy(sizePolicy)
        self.kick_user.setMinimumSize(QtCore.QSize(25, 25))
        self.kick_user.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.kick_user.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"                background-color: transparent;\n"
"                border-radius: 12px;\n"
"            }\n"
"QPushButton:hover {\n"
"                background-color: rgba(255, 255, 255, 0.08);\n"
"            }\n"
" QPushButton:pressed {\n"
"                background-color: rgba(255, 255, 255, 0.15);\n"
"            }")
        self.kick_user.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI/icon/icons8-kick-20.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.kick_user.setIcon(icon1)
        self.kick_user.setIconSize(QtCore.QSize(20, 20))
        self.kick_user.setObjectName("kick_user")
        self.horizontalLayout.addWidget(self.kick_user, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nick_name.setText(_translate("Form", "Имя пользователя"))
