# Form implementation generated from reading ui file 'AuthorizationWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Authorization(object):
    def setupUi(self, Authorization):
        Authorization.setObjectName("Authorization")
        Authorization.resize(750, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Authorization.sizePolicy().hasHeightForWidth())
        Authorization.setSizePolicy(sizePolicy)
        Authorization.setMinimumSize(QtCore.QSize(750, 600))
        Authorization.setMaximumSize(QtCore.QSize(750, 600))
        Authorization.setStyleSheet("")
        self.Wrapper = QtWidgets.QFrame(parent=Authorization)
        self.Wrapper.setGeometry(QtCore.QRect(0, 0, 750, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wrapper.sizePolicy().hasHeightForWidth())
        self.Wrapper.setSizePolicy(sizePolicy)
        self.Wrapper.setMinimumSize(QtCore.QSize(750, 600))
        self.Wrapper.setMaximumSize(QtCore.QSize(700, 500))
        self.Wrapper.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.Wrapper.setStatusTip("")
        self.Wrapper.setStyleSheet("background-color:#101317;")
        self.Wrapper.setObjectName("Wrapper")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Wrapper)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu = QtWidgets.QFrame(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setMinimumSize(QtCore.QSize(600, 400))
        self.menu.setStyleSheet("background-color:rgba(38,40,45,255);\n"
"border-radius:50px;")
        self.menu.setObjectName("menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_4.setContentsMargins(-1, 20, -1, 20)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalFrame = QtWidgets.QFrame(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeWindow = QtWidgets.QPushButton(parent=self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizeWindow.sizePolicy().hasHeightForWidth())
        self.minimizeWindow.setSizePolicy(sizePolicy)
        self.minimizeWindow.setMinimumSize(QtCore.QSize(20, 20))
        self.minimizeWindow.setMaximumSize(QtCore.QSize(20, 20))
        self.minimizeWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.minimizeWindow.setStyleSheet("background-color:green;\n"
"width:20px;\n"
"heigth:20px;\n"
"border-radius:10%;")
        self.minimizeWindow.setText("")
        self.minimizeWindow.setObjectName("minimizeWindow")
        self.horizontalLayout_2.addWidget(self.minimizeWindow, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.closeWindowButton = QtWidgets.QPushButton(parent=self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeWindowButton.sizePolicy().hasHeightForWidth())
        self.closeWindowButton.setSizePolicy(sizePolicy)
        self.closeWindowButton.setMinimumSize(QtCore.QSize(20, 20))
        self.closeWindowButton.setMaximumSize(QtCore.QSize(20, 20))
        self.closeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.closeWindowButton.setStyleSheet("background-color:red;\n"
"width:20px;\n"
"heigth:20px;\n"
"border-radius:10%;")
        self.closeWindowButton.setText("")
        self.closeWindowButton.setObjectName("closeWindowButton")
        self.horizontalLayout_2.addWidget(self.closeWindowButton)
        self.verticalLayout_4.addWidget(self.horizontalFrame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Welcome = QtWidgets.QFrame(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Welcome.sizePolicy().hasHeightForWidth())
        self.Welcome.setSizePolicy(sizePolicy)
        self.Welcome.setMinimumSize(QtCore.QSize(300, 100))
        self.Welcome.setMaximumSize(QtCore.QSize(300, 100))
        self.Welcome.setStyleSheet("")
        self.Welcome.setObjectName("Welcome")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Welcome)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.Welcome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("text-align:center;\n"
"color:white;\n"
"font-size:26px;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(parent=self.Welcome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color:white;\n"
"font-size:24px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.Welcome, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.Login = QtWidgets.QFrame(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login.sizePolicy().hasHeightForWidth())
        self.Login.setSizePolicy(sizePolicy)
        self.Login.setMinimumSize(QtCore.QSize(500, 100))
        self.Login.setObjectName("Login")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Login)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.Login_input = QtWidgets.QLineEdit(parent=self.Login)
        self.Login_input.setMinimumSize(QtCore.QSize(250, 0))
        self.Login_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.Login_input.setText("")
        self.Login_input.setObjectName("Login_input")
        self.verticalLayout_5.addWidget(self.Login_input)
        self.verticalLayout_4.addWidget(self.Login, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Password = QtWidgets.QFrame(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Password.sizePolicy().hasHeightForWidth())
        self.Password.setSizePolicy(sizePolicy)
        self.Password.setMinimumSize(QtCore.QSize(500, 100))
        self.Password.setObjectName("Password")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Password)
        self.verticalLayout_6.setContentsMargins(10, 1, 10, 1)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.Password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.Password_input = QtWidgets.QLineEdit(parent=self.Password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Password_input.sizePolicy().hasHeightForWidth())
        self.Password_input.setSizePolicy(sizePolicy)
        self.Password_input.setMinimumSize(QtCore.QSize(250, 0))
        self.Password_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.Password_input.setObjectName("Password_input")
        self.verticalLayout_6.addWidget(self.Password_input)
        self.ForgotPasswordButton = QtWidgets.QToolButton(parent=self.Password)
        self.ForgotPasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ForgotPasswordButton.setStyleSheet("\n"
"    color:white;\n"
"    text-decoration:underline white;\n"
"    font-size:16px;\n"
"\n"
"")
        self.ForgotPasswordButton.setObjectName("ForgotPasswordButton")
        self.verticalLayout_6.addWidget(self.ForgotPasswordButton, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_4.addWidget(self.Password, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.SignIn = QtWidgets.QFrame(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignIn.sizePolicy().hasHeightForWidth())
        self.SignIn.setSizePolicy(sizePolicy)
        self.SignIn.setMinimumSize(QtCore.QSize(500, 100))
        self.SignIn.setObjectName("SignIn")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SignIn)
        self.verticalLayout_7.setContentsMargins(10, 1, 10, 1)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SignInButton = QtWidgets.QPushButton(parent=self.SignIn)
        self.SignInButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.SignInButton.setStyleSheet("QPushButton {\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#323338;\n"
"font-size:16px;\n"
"color:#808994;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:#656c76;\n"
"color:black;\n"
"}")
        self.SignInButton.setObjectName("SignInButton")
        self.verticalLayout_7.addWidget(self.SignInButton)
        self.verticalLayout_4.addWidget(self.SignIn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Register = QtWidgets.QFrame(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Register.sizePolicy().hasHeightForWidth())
        self.Register.setSizePolicy(sizePolicy)
        self.Register.setMinimumSize(QtCore.QSize(300, 40))
        self.Register.setStyleSheet("color:white;")
        self.Register.setObjectName("Register")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Register)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("font-size:18px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_4.addWidget(self.Register, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.menu, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Authorization)
        QtCore.QMetaObject.connectSlotsByName(Authorization)

    def retranslateUi(self, Authorization):
        _translate = QtCore.QCoreApplication.translate
        Authorization.setWindowTitle(_translate("Authorization", "Авторизация"))
        self.label.setText(_translate("Authorization", "Добро пожаловать!"))
        self.label_2.setText(_translate("Authorization", "Войдите в акканут"))
        self.label_3.setText(_translate("Authorization", "Логин/Почта"))
        self.label_4.setText(_translate("Authorization", "Пароль"))
        self.ForgotPasswordButton.setText(_translate("Authorization", "Забыли пароль?"))
        self.SignInButton.setText(_translate("Authorization", "Войти"))
        self.pushButton.setText(_translate("Authorization", "Нет акканута? - Зарегестрироваться"))
