# Form implementation generated from reading ui file 'ContextMenuicon.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(290, 190)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(290, 190))
        Frame.setMaximumSize(QtCore.QSize(290, 190))
        Frame.setStyleSheet("QFrame {\n"
"background-color: #242429; /* Тёмно-серый фон */\n"
"border-radius: 20%;\n"
"}")
        self.ProfileButton = QtWidgets.QPushButton(parent=Frame)
        self.ProfileButton.setGeometry(QtCore.QRect(10, 20, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ProfileButton.setFont(font)
        self.ProfileButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ProfileButton.setStyleSheet("QPushButton {\n"
"    border-radius: 5%;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    text-align: left;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(229, 229, 229, 55);\n"
"}")
        self.ProfileButton.setObjectName("ProfileButton")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=Frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 100, 271, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.LabelLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.LabelLayout.setContentsMargins(0, 0, 0, 0)
        self.LabelLayout.setObjectName("LabelLayout")
        self.NameLabel = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NameLabel.sizePolicy().hasHeightForWidth())
        self.NameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NameLabel.setFont(font)
        self.NameLabel.setStyleSheet("color: white;")
        self.NameLabel.setObjectName("NameLabel")
        self.LabelLayout.addWidget(self.NameLabel)
        self.HeadphonesVolume = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HeadphonesVolume.sizePolicy().hasHeightForWidth())
        self.HeadphonesVolume.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HeadphonesVolume.setFont(font)
        self.HeadphonesVolume.setStyleSheet("color: white;")
        self.HeadphonesVolume.setObjectName("HeadphonesVolume")
        self.LabelLayout.addWidget(self.HeadphonesVolume, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.SliderVoice = QtWidgets.QSlider(parent=Frame)
        self.SliderVoice.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SliderVoice.setFont(font)
        self.SliderVoice.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SplitHCursor))
        self.SliderVoice.setStyleSheet("QSlider{\n"
"                background-color:None;\n"
"            }\n"
"            QSlider::groove:horizontal {  \n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.SliderVoice.setMaximum(30)
        self.SliderVoice.setProperty("value", 10)
        self.SliderVoice.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.SliderVoice.setObjectName("SliderVoice")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.ProfileButton.setText(_translate("Frame", "Профиль"))
        self.NameLabel.setText(_translate("Frame", "Громкость звука:"))
        self.HeadphonesVolume.setText(_translate("Frame", "1.0"))
