# Form implementation generated from reading ui file 'MiniUserIcon.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mini_Icon(object):
    def setupUi(self, Mini_Icon):
        Mini_Icon.setObjectName("Mini_Icon")
        Mini_Icon.resize(400, 300)
        self.widget_2 = QtWidgets.QWidget(parent=Mini_Icon)
        self.widget_2.setGeometry(QtCore.QRect(110, 100, 20, 20))
        self.widget_2.setMinimumSize(QtCore.QSize(20, 20))
        self.widget_2.setMaximumSize(QtCore.QSize(20, 20))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.UsersLogoinChat = QtWidgets.QPushButton(parent=self.widget_2)
        self.UsersLogoinChat.setGeometry(QtCore.QRect(0, 0, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UsersLogoinChat.sizePolicy().hasHeightForWidth())
        self.UsersLogoinChat.setSizePolicy(sizePolicy)
        self.UsersLogoinChat.setMinimumSize(QtCore.QSize(20, 20))
        self.UsersLogoinChat.setMaximumSize(QtCore.QSize(20, 20))
        self.UsersLogoinChat.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.UsersLogoinChat.setStyleSheet("background-color:purple;\n"
"border-radius:10px;\n"
"color:White;\n"
"font-size:12px;\n"
"text-align:center;\n"
"")
        self.UsersLogoinChat.setObjectName("UsersLogoinChat")

        self.retranslateUi(Mini_Icon)
        QtCore.QMetaObject.connectSlotsByName(Mini_Icon)

    def retranslateUi(self, Mini_Icon):
        _translate = QtCore.QCoreApplication.translate
        Mini_Icon.setWindowTitle(_translate("Mini_Icon", "Form"))
        self.UsersLogoinChat.setText(_translate("Mini_Icon", "G"))
