# Form implementation generated from reading ui file 'UserIcon.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Icon(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setGeometry(QtCore.QRect(110, 60, 120, 120))
        self.widget_2.setMinimumSize(QtCore.QSize(120, 120))
        self.widget_2.setStyleSheet("QWidget#widget_2 {\n"
"background:none;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border:3px solid white;\n"
"    border-radius:50%;\n"
"    color:white;\n"
"    font-size:30px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.User2_icon_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.User2_icon_2.setGeometry(QtCore.QRect(10, 10, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.User2_icon_2.sizePolicy().hasHeightForWidth())
        self.User2_icon_2.setSizePolicy(sizePolicy)
        self.User2_icon_2.setMinimumSize(QtCore.QSize(100, 100))
        self.User2_icon_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.User2_icon_2.setStyleSheet("")
        self.User2_icon_2.setObjectName("User2_icon_2")
        self.user2_headphonesMute_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.user2_headphonesMute_2.setGeometry(QtCore.QRect(80, 70, 35, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user2_headphonesMute_2.sizePolicy().hasHeightForWidth())
        self.user2_headphonesMute_2.setSizePolicy(sizePolicy)
        self.user2_headphonesMute_2.setMinimumSize(QtCore.QSize(35, 35))
        self.user2_headphonesMute_2.setMaximumSize(QtCore.QSize(35, 35))
        self.user2_headphonesMute_2.setStyleSheet("border:5px solid #BB271A;\n"
"background-color:#BB271A;\n"
"border-radius:17%;")
        self.user2_headphonesMute_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/headset_off_28dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.user2_headphonesMute_2.setIcon(icon)
        self.user2_headphonesMute_2.setIconSize(QtCore.QSize(23, 23))
        self.user2_headphonesMute_2.setObjectName("user2_headphonesMute_2")
        self.user2_micMute_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.user2_micMute_2.setGeometry(QtCore.QRect(10, 70, 35, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user2_micMute_2.sizePolicy().hasHeightForWidth())
        self.user2_micMute_2.setSizePolicy(sizePolicy)
        self.user2_micMute_2.setMinimumSize(QtCore.QSize(35, 35))
        self.user2_micMute_2.setMaximumSize(QtCore.QSize(35, 35))
        self.user2_micMute_2.setStyleSheet("border:5px solid #BB271A;\n"
"background-color:#BB271A;\n"
"border-radius:17%;")
        self.user2_micMute_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/mic_off_28dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.user2_micMute_2.setIcon(icon1)
        self.user2_micMute_2.setIconSize(QtCore.QSize(23, 23))
        self.user2_micMute_2.setObjectName("user2_micMute_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.User2_icon_2.setText(_translate("Form", "U"))
