# Form implementation generated from reading ui file 'Requests.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(771, 818)
        self.Column = QtWidgets.QFrame(parent=Form)
        self.Column.setGeometry(QtCore.QRect(10, 60, 741, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Column.sizePolicy().hasHeightForWidth())
        self.Column.setSizePolicy(sizePolicy)
        self.Column.setMinimumSize(QtCore.QSize(50, 50))
        self.Column.setStyleSheet("background-color:rgba(16,19,23,255);")
        self.Column.setObjectName("Column")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Column)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.requests_layout = QtWidgets.QFrame(parent=self.Column)
        self.requests_layout.setStyleSheet("QListWidget {\n"
"background:transparent;\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"QListWidget::item\n"
"{\n"
"    background:none; \n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"           border:none;\n"
"            width:10px;\n"
"             height:20px;\n"
"                                                            \n"
"  }\n"
"                                                        \n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"         heigth:0;\n"
" }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"               background: none;\n"
" }\n"
"  QScrollBar::add-line:vertical {\n"
"               height: 0px;\n"
"  }\n"
" QScrollBar::sub-line:vertical {\n"
"                 height: 0px;\n"
" }\n"
"QScrollBar::handle:vertical {\n"
"               background: orange;\n"
"                min-height:10px;\n"
"                 border-radius: 5px;\n"
" }")
        self.requests_layout.setObjectName("requests_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.requests_layout)
        self.verticalLayout_3.setContentsMargins(15, 0, 15, 0)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.my_requests = QtWidgets.QListWidget(parent=self.requests_layout)
        self.my_requests.setMinimumSize(QtCore.QSize(200, 0))
        self.my_requests.setStyleSheet("QListWidget {\n"
"border:1px solid rgba(38,40,45,255);\n"
"border-left:none;\n"
"border-right:none;\n"
"border-top:none;\n"
"}\n"
"\n"
"")
        self.my_requests.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.my_requests.setObjectName("my_requests")
        self.verticalLayout_3.addWidget(self.my_requests)
        self.others_request = QtWidgets.QListWidget(parent=self.requests_layout)
        self.others_request.setMinimumSize(QtCore.QSize(200, 0))
        self.others_request.setStyleSheet("")
        self.others_request.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.others_request.setObjectName("others_request")
        self.verticalLayout_3.addWidget(self.others_request)
        self.verticalLayout_2.addWidget(self.requests_layout)
        self.verticalLayout_2.setStretch(0, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
