# Form implementation generated from reading ui file 'VoiceParameters.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VoiceParams(object):
    def setupUi(self, VoiceParams):
        VoiceParams.setObjectName("VoiceParams")
        VoiceParams.resize(1067, 700)
        VoiceParams.setStyleSheet("background-color:black;\n"
"padding:0px;\n"
"margin:0px;")
        self.TopBar = QtWidgets.QFrame(parent=VoiceParams)
        self.TopBar.setGeometry(QtCore.QRect(0, 0, 1067, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopBar.sizePolicy().hasHeightForWidth())
        self.TopBar.setSizePolicy(sizePolicy)
        self.TopBar.setMinimumSize(QtCore.QSize(0, 100))
        self.TopBar.setStyleSheet("background-color:rgba(34,35,39,255);")
        self.TopBar.setObjectName("TopBar")
        self.TopBar_10 = QtWidgets.QHBoxLayout(self.TopBar)
        self.TopBar_10.setContentsMargins(35, -1, -1, -1)
        self.TopBar_10.setObjectName("TopBar_10")
        self.label_1 = QtWidgets.QLabel(parent=self.TopBar)
        self.label_1.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_1.setAutoFillBackground(False)
        self.label_1.setStyleSheet("color:white;\n"
"border:none;\n"
"font-size:30px;")
        self.label_1.setObjectName("label_1")
        self.TopBar_10.addWidget(self.label_1, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(parent=VoiceParams)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 311, 82))
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color:white;\n"
"border:none;\n"
"font-size:20px;\n"
"background-color:black;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(parent=VoiceParams)
        self.label_6.setGeometry(QtCore.QRect(60, 330, 311, 82))
        self.label_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("color:white;\n"
"border:none;\n"
"font-size:20px;\n"
"background-color:black;\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalSlider = QtWidgets.QSlider(parent=VoiceParams)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 420, 551, 31))
        font = QtGui.QFont()
        font.setKerning(True)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setStyleSheet("QSlider{\n"
"                background: black;\n"
"            }\n"
"            QSlider::groove:horizontal {  \n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"            QSlider::handle:horizontal {\n"
"                background: #fff;\n"
"                border: 1px solid #E3DEE2;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"            QSlider::sub-page:qlineargradient {\n"
"                background: #3B99FC;\n"
"                border-radius: 5px;\n"
"            }")
        self.horizontalSlider.setMinimum(-10)
        self.horizontalSlider.setMaximum(30)
        self.horizontalSlider.setProperty("value", 10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_7 = QtWidgets.QLabel(parent=VoiceParams)
        self.label_7.setGeometry(QtCore.QRect(170, 470, 311, 21))
        self.label_7.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("color:white;\n"
"border:none;\n"
"font-size:18px;\n"
"background-color:black;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(parent=VoiceParams)
        self.pushButton.setGeometry(QtCore.QRect(70, 280, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(VoiceParams)
        QtCore.QMetaObject.connectSlotsByName(VoiceParams)

    def retranslateUi(self, VoiceParams):
        _translate = QtCore.QCoreApplication.translate
        VoiceParams.setWindowTitle(_translate("VoiceParams", "Form"))
        self.label_1.setText(_translate("VoiceParams", "Настройки звукового чата"))
        self.label_2.setText(_translate("VoiceParams", "Включение шумоподавления"))
        self.label_6.setText(_translate("VoiceParams", "Настройка громкости микрофона"))
        self.label_7.setText(_translate("VoiceParams", "Громкость микрофона: 1.0"))
        self.pushButton.setText(_translate("VoiceParams", "PushButton"))
