# Form implementation generated from reading ui file 'Friends.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Friends_page(object):
    def setupUi(self, Friends_page):
        Friends_page.setObjectName("Friends_page")
        Friends_page.resize(683, 577)
        self.verticalLayout = QtWidgets.QVBoxLayout(Friends_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Wrapper = QtWidgets.QFrame(parent=Friends_page)
        self.Wrapper.setStyleSheet("background-color:rgba(16,19,23,255);")
        self.Wrapper.setObjectName("Wrapper")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Wrapper)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 11)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu = QtWidgets.QFrame(parent=self.Wrapper)
        self.menu.setMinimumSize(QtCore.QSize(100, 100))
        self.menu.setStyleSheet("QFrame {\n"
"    border-bottom:3px solid white;\n"
"    background-color:rgba(34,35,39,255);\n"
"}\n"
"QPushButton {\n"
"    color: white;\n"
"    font-size:22px;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    background-color:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Эффект туманности сверху с прозрачностью */\n"
"    background-color: rgba(229, 229, 229, 55)\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgba(229, 229, 229, 55);\n"
"}\n"
"")
        self.menu.setObjectName("menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout.setContentsMargins(0, 11, 1, 11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_friend = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_friend.sizePolicy().hasHeightForWidth())
        self.add_friend.setSizePolicy(sizePolicy)
        self.add_friend.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/person_add_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_friend.setIcon(icon)
        self.add_friend.setIconSize(QtCore.QSize(30, 30))
        self.add_friend.setCheckable(False)
        self.add_friend.setAutoRepeat(False)
        self.add_friend.setObjectName("add_friend")
        self.horizontalLayout.addWidget(self.add_friend)
        self.requests = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requests.sizePolicy().hasHeightForWidth())
        self.requests.setSizePolicy(sizePolicy)
        self.requests.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.requests.setCheckable(False)
        self.requests.setObjectName("requests")
        self.horizontalLayout.addWidget(self.requests)
        self.friends = QtWidgets.QPushButton(parent=self.menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.friends.sizePolicy().hasHeightForWidth())
        self.friends.setSizePolicy(sizePolicy)
        self.friends.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.friends.setObjectName("friends")
        self.horizontalLayout.addWidget(self.friends)
        self.verticalLayout_2.addWidget(self.menu)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.Wrapper)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.Wrapper)

        self.retranslateUi(Friends_page)
        QtCore.QMetaObject.connectSlotsByName(Friends_page)

    def retranslateUi(self, Friends_page):
        _translate = QtCore.QCoreApplication.translate
        Friends_page.setWindowTitle(_translate("Friends_page", "Form"))
        self.add_friend.setText(_translate("Friends_page", "Добавить"))
        self.requests.setText(_translate("Friends_page", "Заявки"))
        self.friends.setText(_translate("Friends_page", "Все друзья"))
