# Generated by Django 5.2.4 on 2025-07-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='user1_id',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user2_id',
            new_name='user2',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
