# Generated by Django 5.2.4 on 2025-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0002_rename_user1_id_friendship_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user1', 'user2')},
        ),
    ]
