# Generated by Django 5.2.4 on 2025-08-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0003_users_last_online_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZcordDB.friendship'),
        ),
    ]
