# Generated by Django 5.2.4 on 2025-08-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0004_alter_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='updated_at',
        ),
    ]
