# Generated by Django 5.2.4 on 2025-09-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0006_remove_message_updated_at_friendship_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='friendsadding',
            name='friendship',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_id', to='ZcordDB.friendship'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='friendsadding',
            unique_together={('receiver', 'sender')},
        ),
    ]
