# Generated by Django 5.2.4 on 2025-10-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0007_alter_message_options_friendsadding_friendship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='GroupsMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(choices=[(True, 'ADMIN'), (False, 'NOT_ADMIN')], default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZcordDB.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZcordDB.users')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='ZcordDB.GroupsMembers', to='ZcordDB.users'),
        ),
    ]
