# Generated by Django 5.2.4 on 2025-10-15 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0008_groups_groupsmembers_groups_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False)),
                ('DM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ZcordDB.friendship')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ZcordDB.groups')),
            ],
        ),
    ]
