# Generated by Django 5.2.4 on 2025-11-03 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0010_alter_message_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZcordDB.chats')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZcordDB.groups')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZcordDB.users')),
            ],
        ),
    ]
