# Generated by Django 5.2.4 on 2025-11-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0011_grouprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequest',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invite_receiver', to='ZcordDB.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_sender', to='ZcordDB.users'),
        ),
    ]
