# Generated by Django 5.2.4 on 2025-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0012_grouprequest_receiver_alter_grouprequest_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('service', 'Сервисное'), ('image', 'Картинка'), ('voice', 'Голосовое')], default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='voice/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
