# Generated by Django 5.2.4 on 2025-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0013_message_image_url_message_type_message_voice_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='service_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
