# Generated by Django 5.2.4 on 2025-11-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0014_message_service_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_invite_from_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groups',
            name='is_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groups',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groups',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
