# Generated by Django 5.2.4 on 2025-11-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0015_groups_is_invite_from_admin_groups_is_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='user_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='ZcordDB.users'),
            preserve_default=False,
        ),
    ]
