# Generated by Django 5.2.4 on 2025-12-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0016_groups_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprequest',
            name='chat',
        ),
    ]
