# Generated by Django 5.2.4 on 2025-12-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZcordDB', '0017_remove_grouprequest_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='ZcordDB.groups'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(blank=True),
        ),
    ]
