services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=256MB
      -c max_connections=100
      -c work_mem=8MB
      -c maintenance_work_mem=128MB
      -c effective_cache_size=512MB
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    networks:
      - app-network

  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      DB_HOST: lskwdfvj
      DB_PORT: "5432"
      DJANGO_SETTINGS_MODULE: API.settings
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge