# Form implementation generated from reading ui file 'GroupInfo.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupInfo(object):
    def setupUi(self, GroupInfo):
        GroupInfo.setObjectName("GroupInfo")
        GroupInfo.resize(525, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GroupInfo.sizePolicy().hasHeightForWidth())
        GroupInfo.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(GroupInfo)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Wrapper = QtWidgets.QFrame(parent=GroupInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wrapper.sizePolicy().hasHeightForWidth())
        self.Wrapper.setSizePolicy(sizePolicy)
        self.Wrapper.setMinimumSize(QtCore.QSize(400, 0))
        self.Wrapper.setStyleSheet("QFrame {\n"
"background-color:rgba(16,19,23,255);\n"
"border:1px solid white;\n"
"border-radius:45px;\n"
"}")
        self.Wrapper.setObjectName("Wrapper")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Wrapper)
        self.verticalLayout.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.FriendsList = QtWidgets.QFrame(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FriendsList.sizePolicy().hasHeightForWidth())
        self.FriendsList.setSizePolicy(sizePolicy)
        self.FriendsList.setStyleSheet("border:none;")
        self.FriendsList.setObjectName("FriendsList")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FriendsList)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.change_name = QtWidgets.QFrame(parent=self.FriendsList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_name.sizePolicy().hasHeightForWidth())
        self.change_name.setSizePolicy(sizePolicy)
        self.change_name.setObjectName("change_name")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.change_name)
        self.horizontalLayout_3.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.change_name)
        self.label_3.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.group_name_label = QtWidgets.QLabel(parent=self.change_name)
        self.group_name_label.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;\n"
"")
        self.group_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.group_name_label.setObjectName("group_name_label")
        self.horizontalLayout_3.addWidget(self.group_name_label)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_4.addWidget(self.change_name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.date_of_creation = QtWidgets.QFrame(parent=self.FriendsList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_of_creation.sizePolicy().hasHeightForWidth())
        self.date_of_creation.setSizePolicy(sizePolicy)
        self.date_of_creation.setObjectName("date_of_creation")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.date_of_creation)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.date_of_creation)
        self.label_4.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dat_of_creation_label = QtWidgets.QLabel(parent=self.date_of_creation)
        self.dat_of_creation_label.setStyleSheet("color:white;\n"
"font-size:18px;\n"
"border:none;\n"
"")
        self.dat_of_creation_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dat_of_creation_label.setObjectName("dat_of_creation_label")
        self.horizontalLayout_4.addWidget(self.dat_of_creation_label)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.verticalLayout_4.addWidget(self.date_of_creation, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.is_password = QtWidgets.QCheckBox(parent=self.FriendsList)
        self.is_password.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_password.setObjectName("is_password")
        self.verticalLayout_4.addWidget(self.is_password)
        self.is_private = QtWidgets.QCheckBox(parent=self.FriendsList)
        self.is_private.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_private.setObjectName("is_private")
        self.verticalLayout_4.addWidget(self.is_private)
        self.is_inviteGromAdmin = QtWidgets.QCheckBox(parent=self.FriendsList)
        self.is_inviteGromAdmin.setStyleSheet("QCheckBox {\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid orange;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #rgb(255, 170, 0);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: orange;\n"
"}")
        self.is_inviteGromAdmin.setObjectName("is_inviteGromAdmin")
        self.verticalLayout_4.addWidget(self.is_inviteGromAdmin)
        self.verticalLayout.addWidget(self.FriendsList)
        self.horizontalLayout.addWidget(self.Wrapper, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(GroupInfo)
        QtCore.QMetaObject.connectSlotsByName(GroupInfo)

    def retranslateUi(self, GroupInfo):
        _translate = QtCore.QCoreApplication.translate
        GroupInfo.setWindowTitle(_translate("GroupInfo", "Form"))
        self.label_2.setText(_translate("GroupInfo", "Информация о группе"))
        self.label_3.setText(_translate("GroupInfo", "Название:"))
        self.group_name_label.setText(_translate("GroupInfo", "BYDLO_BYDLO2"))
        self.label_4.setText(_translate("GroupInfo", "Дата создания:"))
        self.dat_of_creation_label.setText(_translate("GroupInfo", "0.0.0"))
        self.is_password.setText(_translate("GroupInfo", "Вход по паролю"))
        self.is_private.setText(_translate("GroupInfo", "Приватная группа (только по приглашению)"))
        self.is_inviteGromAdmin.setText(_translate("GroupInfo", "Приглашения только от администратора"))
