# Form implementation generated from reading ui file 'EnterGroupPassword.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupPassword(object):
    def setupUi(self, GroupPassword):
        GroupPassword.setObjectName("GroupPassword")
        GroupPassword.resize(778, 640)
        self.GP_Wrapper = QtWidgets.QFrame(parent=GroupPassword)
        self.GP_Wrapper.setGeometry(QtCore.QRect(100, 70, 601, 371))
        self.GP_Wrapper.setStyleSheet("#GP_Wrapper {\n"
"background-color:rgba(16,19,23,255);\n"
"border:1px solid white;\n"
"border-radius:45px;\n"
"}")
        self.GP_Wrapper.setObjectName("GP_Wrapper")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GP_Wrapper)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Wrapper = QtWidgets.QFrame(parent=self.GP_Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wrapper.sizePolicy().hasHeightForWidth())
        self.Wrapper.setSizePolicy(sizePolicy)
        self.Wrapper.setMinimumSize(QtCore.QSize(500, 0))
        self.Wrapper.setObjectName("Wrapper")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Wrapper)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spinner_frame = QtWidgets.QFrame(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinner_frame.sizePolicy().hasHeightForWidth())
        self.spinner_frame.setSizePolicy(sizePolicy)
        self.spinner_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.spinner_frame.setObjectName("spinner_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.spinner_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.spinner_layout = QtWidgets.QHBoxLayout()
        self.spinner_layout.setObjectName("spinner_layout")
        self.label_4 = QtWidgets.QLabel(parent=self.spinner_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("color:white;\n"
"font-size:16px;")
        self.label_4.setObjectName("label_4")
        self.spinner_layout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addLayout(self.spinner_layout)
        self.verticalLayout_2.addWidget(self.spinner_frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=self.Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color:white;\n"
"font-size:18px;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.GroupPassword_input = QtWidgets.QLineEdit(parent=self.Wrapper)
        self.GroupPassword_input.setMinimumSize(QtCore.QSize(250, 0))
        self.GroupPassword_input.setStyleSheet("QLineEdit{ \n"
"width:250px;\n"
"height:30px;\n"
"border: 2px solid #323338;\n"
"border-radius: 10px;\n"
"background-color:#1e1f22;\n"
"font-size:16px;\n"
"color:#808994;\n"
"text-align:left;\n"
"padding-left:27px;\n"
"}\n"
"\n"
"")
        self.GroupPassword_input.setInputMask("")
        self.GroupPassword_input.setText("")
        self.GroupPassword_input.setMaxLength(50)
        self.GroupPassword_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.GroupPassword_input.setObjectName("GroupPassword_input")
        self.verticalLayout_2.addWidget(self.GroupPassword_input)
        self.verticalLayout.addWidget(self.Wrapper, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.Errors = QtWidgets.QFrame(parent=self.GP_Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Errors.sizePolicy().hasHeightForWidth())
        self.Errors.setSizePolicy(sizePolicy)
        self.Errors.setMinimumSize(QtCore.QSize(500, 70))
        self.Errors.setStyleSheet("\n"
"border:4px solid #BF092F;\n"
"border-radius:25%;")
        self.Errors.setObjectName("Errors")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.Errors)
        self.vboxlayout.setContentsMargins(20, 10, -1, 10)
        self.vboxlayout.setObjectName("vboxlayout")
        self.ErrorText = QtWidgets.QLabel(parent=self.Errors)
        self.ErrorText.setStyleSheet("border:none;\n"
"font-size:18px;\n"
"color:#BF092F;")
        self.ErrorText.setObjectName("ErrorText")
        self.vboxlayout.addWidget(self.ErrorText)
        self.verticalLayout.addWidget(self.Errors, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.join_group = QtWidgets.QPushButton(parent=self.GP_Wrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.join_group.sizePolicy().hasHeightForWidth())
        self.join_group.setSizePolicy(sizePolicy)
        self.join_group.setMinimumSize(QtCore.QSize(151, 50))
        self.join_group.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.join_group.setStyleSheet(" QPushButton {\n"
"border:1px solid orange;\n"
"border-radius:25%;\n"
"background-color:orange;\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 211, 121, 200);\n"
"    border:1px solid rgba(255, 211, 121, 200);\n"
"}")
        self.join_group.setObjectName("join_group")
        self.verticalLayout.addWidget(self.join_group, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(GroupPassword)
        QtCore.QMetaObject.connectSlotsByName(GroupPassword)

    def retranslateUi(self, GroupPassword):
        _translate = QtCore.QCoreApplication.translate
        GroupPassword.setWindowTitle(_translate("GroupPassword", "Form"))
        self.label_4.setText(_translate("GroupPassword", "Проверяем пароль"))
        self.label.setText(_translate("GroupPassword", "Введите пароль:"))
        self.GroupPassword_input.setPlaceholderText(_translate("GroupPassword", "Введите пароль"))
        self.ErrorText.setText(_translate("GroupPassword", "Ошибка: поле \"Название группы\" не было заполнено"))
        self.join_group.setText(_translate("GroupPassword", "Войти"))
